### ISSUE TITLE
Open and focus date-picker with label

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-date-picker#124]
Should date-picker be opened after label click? Or at least focused?
[https://jsbin.com/kiwonecoge/7/edit?html,output](https://jsbin.com/kiwonecoge/7/edit?html,output)

**Comment by tomivirkki** [comment]
If you change the input field to paper-input in your example it doesn't focus on label click. I don't think this is expected from vaadin-date-picker either.
