### ISSUE TITLE
Year scroller partially hidden on narrow screens

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-date-picker#131]
When screen width is ~ 421 - 470 pixels, the year scroller is partially hidden.

Windows 10
Chrome 49.0.2623.87 & IE 11
![date_picker_bug](https://cloud.githubusercontent.com/assets/8615573/13913434/550663f2-ef4f-11e5-85db-f2548dd7e2b2.PNG)

**Comment by jouni** [comment]
Can’t reproduce any more with the latest v3 beta. Considering this fixed.
