### ISSUE TITLE
Wrong click events when inside scroll container

### ISSUE THREAD

**Issue by fleckdalm** [vaadin/vaadin-date-picker#134]
If i put the component inside a scroll container and scroll down a bit the dialog is wrongly positioned and moreover all click events lead to wrong results (e.g. wrong day clicked).

**Comment by tomivirkki** [comment]
Hi, seems that the dropdown wasn't repositioned/realigned on the container scroll. Fixed that in #137 (merged to master branch now).
Does the change also fix the click issue you mentioned (couldn't reproduce it myself)?

**Comment by fleckdalm** [comment]
Thanks!
Unfortunately it didn't resolve the click issue but I think it is related to #133

**Comment by jounik** [comment]
@fleckdalm, would it be possible to get a test case for this (jsbin, plunkr, etc.), so that we could reproduce it?

**Comment by fleckdalm** [comment]
@jounik the issue is definitely related to #133. It happens when a new stacking context is created.

**Comment by Saulis** [comment]
@fleckdalm are you still having the issue? Could you provide us with an example app where this occurs?

**Comment by fleckdalm** [comment]
@Saulis thank you for the follow up but, as I already mentioned, the issue is related to #133. So if you resolve the other issue this willl get resolved as well.

**Comment by platosha** [comment]
Probably fixed by #347.

Closing for now. Feel free to reopen if still relevant.
