### ISSUE TITLE
Open/Close transition on mobile

### ISSUE THREAD

**Issue by fleckdalm** [vaadin/vaadin-date-picker#153]
The datepicker pops up and closes very abruptly in the mobile layout. 
Could you consider adding some nice transitions for open/close?

**Comment by jounik** [comment]
Definitely have considered that already – just not as a high priority for 1.0.

On top of the popup open/close, we should consider some sort of visual feedback when the user selects a date (a ripple is a natural choice for Material Design).

There’s a similar task for the combo box: https://github.com/vaadin/vaadin-combo-box/issues/65

**Comment by manolo** [comment]
moving this feature to vaadin-overlay https://github.com/vaadin/vaadin-overlay/issues/36

**Comment by jouni** [comment]
We can’t implement these in the generic overlay, as the transition/animation is probably custom for the date picker.

**Comment by jouni** [comment]
> I might want to change my previous statement – I think it would be possible to achieve the desired results with the generic vaadin-overlay animation/transition feature. For example, have a separate animation for the date selection and delay the overlay closing animation until it’s finished.
https://github.com/vaadin/vaadin-overlay/issues/36#issuecomment-355211954

Would be great to prototype this.

**Comment by jouni** [comment]
The new Lumo theme (in v3) has an opening animation currently.

There’s a PR pending for vaadin-overlay that allows us to defined closing animations as well: https://github.com/vaadin/vaadin-overlay/pull/60

We will probably add some closing animation for date picker once that is released. I’ll keep this issue open until we do that.

**Comment by tomivirkki** [comment]
Seems to be working fine with the latest version. Closing.
