### ISSUE TITLE
Clicking the calendar icon no longer closes the dropdown

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#156]
We might need to put the "pointer-events: none" workaround (that was removed in 2bfa222694ac8e508400774e5c1e76c4369c3713) back

**Comment by jouni** [comment]
Broken still with shadow DOM. Either reopen or create a new issue. Your choice :)

You can see the issue in Expense Manager demo and Chrome.

**Comment by tomivirkki** [comment]
Works fine at http://demo.vaadin.com/expense-manager-ng/?dom=shadow

The expense manager at https://demo.vaadin.com/expense-manager/ is using an old version

**Comment by jouni** [comment]
Thanks for looking! Can you test the original expense manager locally? We’re using that.
