### ISSUE TITLE
datePicker.i18n.firstDayOfWeek not working?

### ISSUE THREAD

**Issue by silentHoo** [vaadin/vaadin-date-picker#168]
If I set the value directly (after the element was instanciated), nothing changes. Sunday is still on the first row, if I click on the calendar icon.

    var datePicker = CustomElementHelper.getInstance('#todo-datepicker');
    datePicker.i18n.firstDayOfWeek = 1;

This way works if I set a custom `formatDate` function:

    var datePicker = CustomElementHelper.getInstance('#todo-datepicker');
    datePicker.i18n.formatDate = function(date) {
        return moment(date).format($scope.dateFormat);
    };

Just for the completeness here: `CustomElementHelper.getInstance(selector)` returns `document.querySelector(selector)`.

<img width="414" alt="bildschirmfoto 2016-04-19 um 10 00 21" src="https://cloud.githubusercontent.com/assets/1610894/14631819/95fa2b8c-0615-11e6-8311-29d0f318db1c.png">

**Comment by platosha** [comment]
Hello!

I think, this is why it's not working for your case. You're modifying `firstDayOfWeek`, it’s a sub-property of `i18n` property object. When modifying sub-properties, you have to use Polymer's `.set` method to notify the element about the sub-property changes.

Please, try this way:
```javascript
  datePicker.set('i18n.firstDayOfWeek', 1);
```

Does it solve the issue for you?

**Comment by peterblazejewicz** [comment]
@platosha this should go into docs. Thanks!

**Comment by silentHoo** [comment]
@platosha Okay that works pretty well. Wow, that's cool and works because Polymer adds the `.set` method on the elements prototype 👍 The method then notifies all sub-children that have a binding set up for that sub-property value. Really cool 🤗

I use Angular for my experimental application to test a bit how custom elements work in other frameworks. So I see here the assumption that you as the developer have designed that element for applications that use mainly Polymer. I think if you add this bit of information to the docs (as @peterblazejewicz mentioned) it will be a good starting point for developers that haven't yet done anything with Polymer. Btw: you provide really great elements 👍

**Comment by jouni** [comment]
>  I think if you add this bit of information to the docs (as @peterblazejewicz mentioned) it will be a good starting point for developers that haven't yet done anything with Polymer.
I agree, we should have a mention about this in our documentation. I have actually had that in my todo for a while already, I just haven’t managed to add it in our backlog.

Thanks for the nice feedback 🙇
