### ISSUE TITLE
Use within paper-drawer-panel

### ISSUE THREAD

**Issue by rubenstolk** [vaadin/vaadin-date-picker#173]
Currently the picker renders fine, but not completely fullscreen, rather below the header of the paper-drawer-panel...

**Comment by Saulis** [comment]
Hi!

Would you be able to provide a screenshot or even a code snippet that would reproduce the issue?

Thanks!

**Comment by rubenstolk** [comment]
Hey @Saulis, never mind, I think it has to do with the little complicated structure of our app. We're using https://github.com/bendavis78/paper-date-picker within a `paper-dialog` for now to get by this issue, hopefully a later version of this component will have a feature to specify where in the dom the actual overlay would be rendered. Closing this for now.

**Comment by Saulis** [comment]
We might be migrating to a similar overlay functionality that the vaadin-combo-box is using where the overlay is rendered always as a direct child of the body.

**Comment by rubenstolk** [comment]
I did make a work around where I simply move the `iron-dropdown` to my app's parent and then things seem to work fine.
