### ISSUE TITLE
Using the "next field" button on iOS skips the date picker

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-date-picker#178]
Using the "next field" button on iOS skips the date picker. See attached GIF for a demo.

This seems to be related to having `tabindex="-1"` and a custom `on-focus` listener on the `<input>` element. Not sure how this should behave though, as entering any date values with keyboard is not yet supported.

Originally this issue was reported by @vaadin-marcus as part of the https://github.com/vaadin/expense-manager-demo application.

![date-picker-ios](https://cloud.githubusercontent.com/assets/368220/15171899/afd84f1a-175a-11e6-98c8-5254b24e9603.gif)

**Comment by jouni** [comment]
The input should be focusable, but read-only. Once focused, it should open with the keyboard arrow keys. On iOS (touch devices), I don’t think we should auto-open the popup on focus, so the only way to open it is by tapping the field or calendar icon.

**Comment by samiheikki** [comment]
Update: This is kinda fixed with https://github.com/vaadin/vaadin-date-picker/pull/247.
But in the `vaadin-date-picker-behavior.html` `_noInput` property is computed as true in iOS. Meaning that input can be focused (won't skip it), but pressing any of the keyboard keys won't fill or open the overlay. If `_noInput` would be false then overlay would be open at same as the keyboard.

**Comment by jouni** [comment]
@samiheikki nice catch 👍🏻

We should allow keyboard input on iOS as well, but we should not open the overlay in that case (at least with the current fullscreen implementation, which uses `position: fixed;` which fails on iOS when an input is focused).

When we fix the overlay positioning and stacking context issues (move it under the `<body>`), we should re-evaluate the fullscreen mode design at the same time.

**Comment by web-padawan** [comment]
This is now reported at vaadin/vaadin-text-field#479, so closing this in favor of that issue.
The fix mentioned above was targeting Polymer 1 and is therefore no longer relevant.
