### ISSUE TITLE
"Styling" demo displays no text when date is picked.

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-date-picker#186]
The "Styling" demo produces no content when a date is picked. Nothing populates the input element, even though the value does indeed change.

https://cdn.vaadin.com/vaadin-elements/master/vaadin-date-picker/demo/

**Comment by jouni** [comment]
The problem is actually that the input text color is white.

**Comment by juniperbelmont** [comment]
(－‸ლ)

New issue: make the text not white.
