### ISSUE TITLE
Limit the range of selectable dates (min and/or max)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#197]
The developer should be able to limit the dates the user is allowed to select.

The most common use case for "min" is probably to limit the selection to future dates.

One use case for "max" is to limit the selection to the end of the current year or one year ahead.

If min > max, no days should be selectable.

Both min and max are inclusive, meaning the user is able to select the minimum or maximum date specified.

Draft code:
```html
<!-- Limit selection to "today – end of year" -->
<vaadin-date-picker min="2016-06-17" max="2016-12-31"></vaadin-date-picker>
```
Feel free to come up with better property/attribute names, if you see these confusing or problematic.

The format for the `min` and `max` properties follows the same rules as the `value` property.

If a value outside min or max is set programmatically (or via data binding), the field should be set to invalid state, and an error message should be shown below the field ("Date is not allowed"). The validation message should be added to the i18n object.

**Comment by AmetAlvirde** [comment]
Is this feature going to be released soon? I would love to PR it if not. Can you tell me? :)

**Comment by tehapo** [comment]
Hi @AmetAlvirde,

this feature is on pretty high priority in our backlog, but the implementation has not been started yet. If you are interested in implementing this, a PR would be awesome! 👍 

If you decide to start working on this, please let us know and of course we're happy to help if you have any questions.

**Comment by Saulis** [comment]
ping @AmetAlvirde @nick-woodward going to release this on `1.2.0-alpha1`

**Comment by Ankita-J** [comment]
How to set min Date as current date using above syntax.

**Comment by Saulis** [comment]
@Ankita-J you need to add a computed property for that in your parent element.

**Comment by Ankita-J** [comment]
I tried a lot adding computed property but it does not working.
Please, can you provide syntax for that.
May be somewhere I am doing wrong.

**Comment by Saulis** [comment]
@Ankita-J here you go: https://jsfiddle.net/Saulis/Ledhf0zr/

**Comment by Ankita-J** [comment]
Thanks a Lot @Saulis 
really very thanks

**Comment by Ankita-J** [comment]
@Saulis  the above example is also working in Microsoft edge and Mozilla Firefox.
I tried for both browsers mentioned above.

**Comment by Ankita-J** [comment]
Again I have a question about Vaadin Date picker. Can I change the overlay of vaadin date picker.
I don't want scroller in date picker instead of that user should click on arrow to change month.

**Comment by jouni** [comment]
Hi, @Ankita-J!

Thanks for the question. In the future, can I ask you to post your questions on our Gitter chat (https://gitter.im/vaadin/vaadin-core-elements)? Adding comments to closed issues is not really a good way to communicate, as this issue has nothing to do with the overlay in this case.

Also, if you have clear feature requests, you can always open up new issues here in GitHub, so we can discuss them in the correct context.

But, for your question about the overlay – no, unfortunately, we don’t have any plans to allow you to replace the scroller interface in the overlay. It is something we’ve thought about, so I’m not saying we will never do that. But for now it’s not likely going to happen.
