### ISSUE TITLE
Use app-localize-behavior [🕔2d]

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#199]
### Polymer compatibility

We should be compatible with the standard Polymer way of localising strings and dates.

Not sure what this means for our own i18n property, do we still keep that as well?
### Simultaneous localization of multiple date pickers

As a part of this task, we should make it easy to localize all date-pickers in the app simultaneously, as currently we require the developer to set the i18n object for every individual date-picker separately.

One option that has come up would be to use the global namespace for this, and use that by default (e.g. `window.vaadin.datepicker.i18n`).

**Comment by Saulis** [comment]
TIL, and just  a comment in case this affects our decision on moving forward this or not: `app-localize-behavior` uses [Intl](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl) which requires a polyfill atleast for Safari (desktop and iOS) and Android.

**Comment by jouni** [comment]
Safari 10 (macOS and iOS) has Intl support: https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html (if “ES Internationalization”) is the same thing.

**Comment by Saulis** [comment]
According to this it is: http://caniuse.com/#search=intl

**Comment by tehapo** [comment]
Basics
--

The most important things that `AppLocalizeBehavior` brings in are following.

* `language` – property for the language used in translations (string)
* `resources` – property for translation resources (object)
* `formats` – property for optional custom formats
* `localize` – method for localizing a value, requires that `language` and `resources` are defined

Adding `AppLocalizeBehavior` to `vaadin-date-picker`?
--

We could add the `AppLocalizeBehavior` to our `DatePickerBehavior`. After this is done, we could use the `localize` method to format the displayed input field value as follows.
```javascript
this._inputValue = selectedDate ? this.localize('vaadin-date-picker', 'selected', selectedDate) : '';
```


Seems like `AppLocalizeBehavior` requires the `language` and `resources` properties to be defined for each element separately. It would be convenient to define these once, but in your app you actually need to trickle these values down to each element separately.

```html
<vaadin-date-picker language="[[language]]" resources="[[resources]]" value="2016-01-01"></vaadin-date-picker>
```

```javascript
Polymer({
  is: 'my-app',

  behaviors: [
    Polymer.AppLocalizeBehavior
  ],

  properties: {
    language: {
      value: 'en'
    },
    resources: {
      value: function() {
        return {
          "en": { "vaadin-date-picker": "{selected, date, short}" },
          "fi": { "vaadin-date-picker": "{selected, date, short}" }
        };
      }
    }
  }
});
```

Using `AppLocalizeBehavior` with `vaadin-date-picker`?
--

Another option would be to use the current `i18n` property and define a `formatDate` function that is implemented using the `localize` method. Something like the following.

```javascript
this.$.datePicker.i18n.formatDate = function(selectedDate) {
  return this.localize('vaadin-date-picker', 'selected', selectedDate);
}.bind(this);
```

Multiple languages problem
--

Having multiple translations on the same app is a bit problematic. Seems that internally `AppLocalizeBehavior` uses a shared cache for `IntlMessageFormat` objects, but the cache key does not include the used language. If you would localize two `vaadin-date-picker`s with different language, both of them would eventually get formatted the same way when the value is updated.

**Comment by samiheikki** [comment]
Great research. Thanks @tehapo !

**Comment by jouni** [comment]
Whatever we decide with the date-picker should also apply to upload as well.

**Comment by balloob** [comment]
> Another option would be to use the current `i18n` property and define a `formatDate` function that is implemented using the `localize` method.

The problem with this approach is that right now, representation of the date in the UI is coupled to the internal storage of the date inside the component. This means that if you want to update `formatDate`, you will have to be able to parse that date.

To make it possible, the component should be updated first to either always report dates as Date object (`new Date(YYYY, MM - 1, DD)`) or as ISO8601 date format (`YYYY-MM-DD`)

**Comment by hyyan** [comment]
Any news about this?! wondering if it has been implemented or will be

**Comment by Saulis** [comment]
@hyyan we went to implement our own localization, see here: https://cdn.vaadin.com/vaadin-date-picker/2.0.0-alpha2/demo/advanced.html#localizing

Currently, there are no plans to use `AppLocalizeBehavior` I'm afraid.

**Comment by hyyan** [comment]
Hey @Saulis  , thanks for the fast reply, in the matter of fact I am aware of this property, but  I was looking for a way to integrate this with `AppLocalizeBehavior', it seems there is no optimal way to do it.

Thanks

**Comment by turboborsuk** [comment]
Unfortunately the current approach with `i18n` object does not fully support hot swapping of locale I'm afraid.
It specifically relates to months and week names in `vaadin-month-calendar`.
I've been able to track this issue down to the fact that in e.g.:
```
<div part="weekdays">
  <template is="dom-repeat" items="[[_getWeekDayNames(i18n.weekdays, i18n.weekdaysShort, showWeekNumbers, i18n.firstDayOfWeek)]]">
    <div part="weekday" role="heading" aria-label$="[[item.weekDay]]">[[item.weekDayShort]]</div>
  </template>
</div>
```
the `_getWeekDayNames` method does not observe splices to `weekdays` array.
You can easily verify this by changing the array items and calling a Polymer.set method on showWeekNumbers to trigger recomputing.

**Comment by web-padawan** [comment]
Closing per https://github.com/vaadin/vaadin-date-picker/issues/199#issuecomment-308052897
Polymer set of behaviors is now in the maintenance mode so there is no more reason to introduce this feature. The `i18n` object is the way to go for other Vaadin components, too.
