### ISSUE TITLE
odd behaviour when scrolling outside dialog

### ISSUE THREAD

**Issue by HaykoKoryun** [vaadin/vaadin-date-picker#200]
When scrolling outside the dialog, the dialog exhibits odd behaviour; see the following gif as seen on your [demo](https://vaadin.com/elements/-/element/vaadin-date-picker) page:
![bug](https://cloud.githubusercontent.com/assets/2579764/16232078/292a275e-37da-11e6-9553-aefd508bb502.gif)

A suggestion would be to close the dialog after scrolling outside with a given tolerance.

**Comment by platosha** [comment]
Hi, thanks for reporting this.

We decided to enable the outside scrolling on purpose, to make it easier for our uses to expand the dropdown by scrolling the page, if needed. Though it is indeed an issue that if you scroll the page too far, then the dropdown detaches from its input field.

In `vaadin-combo-box` we solved this by allowing the dropdown to scroll along with the page. Please try it on the [vaadin-combo-box page](https://vaadin.com/elements/-/element/vaadin-combo-box). Would it resolve the issue for you?

**Comment by HaykoKoryun** [comment]
@platosha yes the user experience with `vaadin-combo-box` is better as detaching from the input field when it's initially attached is a bit jarring, especially so when the content of the date-picker is more complex.

**Comment by tomivirkki** [comment]
Fixed in v3.0.0 https://cdn.vaadin.com/vaadin-date-picker/3.0.0-alpha3/demo/#date-picker-basic-demos
