### ISSUE TITLE
angular tests break typescript compilation in angular2-cli

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-date-picker#206]
Error: Typescript found the following errors: tmp/broccoli_type_script_compiler-input_base_path-qtGuLt77.tmp/0/public/bower_components/vaadin-date-picker/test/angular2/main.ts (3, 30): Cannot find module '@vaadin/angular2-polymer'.

**Comment by platosha** [comment]
It is wrong that in angular2-cli projects something tries to compile the typescript files in our elements. Can we prevent it? Maybe add an `{ "exclude": "bower_components" }` line to tsconfig.json?
