### ISSUE TITLE
Implement 'change' event

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-date-picker#207]
Like in vaadin-combo-box we should consider this event, see https://github.com/vaadin/vaadin-combo-box/issues/271

**Comment by robrez** [comment]
It seems that the current `value-changed` event fires when the `vaadin-date-picker` value is changed imperitively (not triggered by user input)... I wonder if it would be agreeable to fix that, as well, when the `change` event is implemented.

**Comment by robrez** [comment]
Still would like to see this implemented;  Currently, vaadin-date-picker uses vaadin-text-field -- which does publish change events;

However events don't propagate accross shadow dom boundaries.  This snippet seems to indicate that vaadin-date-picker would have to play that same game that vaadin-text-field does:

```
    _onChange(e) {
      // In the Shadow DOM, the `change` event is not leaked into the
      // ancestor tree, so we must do this manually.
      const changeEvent = new CustomEvent('change', {
        detail: {
          sourceEvent: e
        },
        bubbles: e.bubbles,
        cancelable: e.cancelable,
      });
      this.dispatchEvent(changeEvent);
    }
```

https://github.com/vaadin/vaadin-text-field/blob/master/src/vaadin-text-field-mixin.html#L250-L257


Alternatively, date-picker-light can be used and change events can be added to the light-dom input.  I'm not really so sure that the events published by the overlay element would be available or sufficient to indicate a user-initiated change occurred. Maybe value diffing on-blur would work there

**Comment by ndormont** [comment]
Probably a noob question: Why not just use `on-value-changed` ?
