### ISSUE TITLE
Problem to implement Vaadin datepicker in angular2-rc4 forms

### ISSUE THREAD

**Issue by abhibly** [vaadin/vaadin-date-picker#208]
Hello Guys i have implemented vaadin date-picker in one of my pages.I want to assign formControl to the vaadin datepicker directive but it is showing error like this
` ORIGINAL EXCEPTION: No value accessor for ' '`
And i have built the form in this way
`<form [formGroup]="myForm"  (ngSubmit)="onSubmit(myForm.value)">
  <div>
<label for="skuInput">SKU</label>
<vaadin-date-picker label="Pick a date" [formControl]="myForm.controls['sku']"></vaadin-date-picker></div>
<button type="submit" class="ui button">Submit</button>
</form>`
And included the datepicker directive like this
`directives: [FORM_DIRECTIVES, REACTIVE_FORM_DIRECTIVES,Date,PolymerElement('vaadin-date-picker')]`
I dont want to use [(ngModel)],i want to get the value using FormControl only.What is the correct way to use vaadin datepicker in angular2 forms? Thanks

**Comment by tomivirkki** [comment]
Hi @abhibly,

FormControl was added to Angular 2 in 2.0.0-RC4 release and we haven't yet updated angular2-polymer to cover that. There's a ticket about it already at https://github.com/vaadin/angular2-polymer/issues/43 so I'm closing this issue for now as a duplicate.

If you wan't to use forms with angular2-polymer, I recommend sticking to the [deprecated API](https://angular.io/docs/ts/latest/guide/forms-deprecated.html) for now until the feature is added.

**Comment by abhibly** [comment]
@tomivirkki Thank you sir,
The link which you gave is template driven forms.Does Vaadin Datepicker supports model driven forms also?

**Comment by abhibly** [comment]
@tomivirkki  Thank You,implemented using model driven depricated forms

**Comment by tomivirkki** [comment]
@abhibly Ok, glad you got it working
