### ISSUE TITLE
Inconsistent fonts across vaadin elements -- Should mirror paper styles. 🖊

### ISSUE THREAD

**Issue by juniperbelmont** [vaadin/vaadin-date-picker#211]
Same issue as https://github.com/vaadin/vaadin-grid/issues/410

Currently, vaadin-grid, vaadin-upload, vaadin-date-picker and vaadin-combo-box treat fonts differently. They should all instead use paper styles as a default and expose mixins for changing styles.

**Comment by manolo** [comment]
Pure Polymer 2.0 will use Vaadin themes, and will not import paper styles.
When designing the MD theme we will share standard modules for all elements, including fonts.

Will not fix in 1.x versions.
