### ISSUE TITLE
Vaadin-date-picker dynamically set a default date using Angular2

### ISSUE THREAD

**Issue by nunna-suma** [vaadin/vaadin-date-picker#219]
Hi

I'm trying to set a default date dynamically in vaadin-date-picker using Angular2. While implementing these task on my project it shows an exception.

![code](https://cloud.githubusercontent.com/assets/8984532/17551805/c6e5505c-5f19-11e6-8ba5-d34fa4385232.png)
![vaadin-date-picker-error](https://cloud.githubusercontent.com/assets/8984532/17551804/c6e414bc-5f19-11e6-8cbd-8d8bead10189.png)

Thank you.

**Comment by tehapo** [comment]
Hi,

I think the problem here is that you are setting the value in an incorrect format, which causes it to be reverted to an empty string.

Please try something like the following. The example uses a ES6/TypeScript template literal, but as you can see the correct format is format is `yyyy-mm-dd`.

```javascript
pad(i: number) {
  return i < 10 ? '0' + i : i;
}

ngOnInit() {
  const selectedDate = new Date();
  this.birthday = `${selectedDate.getFullYear()}-${this.pad(selectedDate.getMonth() + 1)}-${this.pad(selectedDate.getDate())}`;
}
```
