### ISSUE TITLE
Date Picker doesn't display error messages

### ISSUE THREAD

**Issue by nick-woodward** [vaadin/vaadin-date-picker#224]
Seeing how `vaadin-combo-box` and the paper components generally allow for an error-message I would expect the date-picker to be the same.

```html
<vaadin-date-picker required error-message="Some error message"></vaadin-date-picker>
```

**Comment by jouni** [comment]
@tomivirkki, what would it mean to add this? It would probably need some documentation from our side as well, right?

**Comment by nick-woodward** [comment]
@jouni I ended up playing around with it and adding the error-message itself is relatively easy.

**Just a matter of adding a new property and adding:**
```html
<template is="dom-if" if="[[errorMessage]]">
  <paper-input-error aria-live="assertive">[[errorMessage]]</paper-input-error>
</template>
```

Overall the change is fairly simple, however a secondary issue is that the date-picker becomes invalid fairly easily.

### Example

[Live Demo](https://jsbin.com/zihituwati/edit?html,output)
* Click on the input field
* The date picker should pop up and the input will become invalid

### Steps to Reproduce

1. Add `vaadin-date-picker`
2. Add `auto-validate` and `required` to the element

**Comment by tomivirkki** [comment]
@nick-woodward and @jouni The `errorMessage` property might be a reasonable addition to the `vaadin-date-picker` API, especially since it should work nicely inside `iron-form`. 

Note that you can already add any custom content inside the date picker by using `vaadin-date-picker-light` like in the following example:
https://jsfiddle.net/xhfbu5ny/

**Comment by nick-woodward** [comment]
@tomivirkki Awesome, I was unaware the light version was so flexible.

Not overly surprising, but it looks like the light version has the same issue as the regular version regarding validation.

However, it looks like the validation issue is somewhat documented in the code as a [`TODO`](https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L256) comment
