### ISSUE TITLE
Support other date formats

### ISSUE THREAD

**Issue by haasDev** [vaadin/vaadin-date-picker#232]
I would like to see a feature that would allow for other date formats other than ISO 8601 .  I would be willing to work on this feature if others are interested in having this feature and there is a reasonable chance that the pull request would be accepted.

**Comment by jouni** [comment]
Hi!

Are you referring to the `value` of the input? You can customize that using the `i18n.formatDate` property: https://vaadin.com/docs/-/part/elements/vaadin-date-picker/vaadin-date-picker-localization.html

If you already knew about that API, can you be a bit more explicit with the feature you’re looking for? Thanks!

**Comment by jouni** [comment]
@haasDev I’m closing this issue. Go ahead and comment/reopen if you think there’s still something we should do with date formats.
