### ISSUE TITLE
Improve documentation and examples on validation and error handling

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-date-picker#236]
Our current example on custom validation uses `Polymer.IronMeta` to register a validator. This seems to work, but maybe a custom element might be more a clear solution (see the StackOverflow link below).

We should also have some example (or link to existing documentation) on how to display error messages when the field is invalid. Notice also how min/max properties are validated internally by the `vaadin-date-picker`.

See also this for inspiration:
http://stackoverflow.com/questions/34401651/how-to-apply-multiple-validators-to-a-single-paper-input-in-polymer

**Comment by web-padawan** [comment]
Validation demos have been updated, so this issue is no longer relevant. Closing.
