### ISSUE TITLE
Publish to NPM (webpack usage)

### ISSUE THREAD

**Issue by leocaseiro** [vaadin/vaadin-date-picker#240]
Hi, I'm very interested in setup my Angular 2 Application to use this component.

However, I'm not using bower in regards to the webpack.
Are you interested in publish into npm?

Thanks

**Comment by jouni** [comment]
Hi, and thanks for asking!

We are very interested in publishing into npm as well, but currently it’s not a suitable option for us, as we have a lot of Paper element dependencies in Bower, which are not really available in npm. So we are basically waiting for the Polymer team to come up with a solution, and we will follow after that.

You can read more about the troubles with Polymer publishing their elements in npm from this thread: https://github.com/Polymer/polymer/issues/326#issuecomment-207506068

**Comment by leocaseiro** [comment]
Hi @jouni, thank you for your reply.
I'm sorry, I wasn't aware of that.
