### ISSUE TITLE
Error: TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by 25ar** [vaadin/vaadin-date-picker#251]
### Description
I did everything from instruction, but got an error

### Expected outcome
Datapicker

### Actual outcome
error:
Error: TypeError: Cannot read property 'prototype' of undefined
	    at __extends (http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:5:68)
	    at eval (http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:12:5)
	    at Object.eval (http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:23:2)
	    at eval (http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:280:4)
	    at eval (http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js:281:3)
	Evaluating http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/src/polymer-element.js
	Evaluating http://10.10.17.179:8181/node_modules/@vaadin/angular2-polymer/index.js
	Evaluating http://10.10.17.179:8181/js/app.module.js
	Evaluating http://10.10.17.179:8181/js/main.js
	Error loading http://10.10.17.179:8181/js/main.js

### Steps to reproduce
1) bower install polymer iron-flex-layout iron-icons app-layout paper-styles paper-icon-button paper-input vaadin-grid vaadin-date-picker
2) npm install @vaadin/angular2-polymer
3) Add to index.html head:

    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="bower_components/vaadin-date-picker/vaadin-date-picker.html">

4) My systemjs.config.js:
var map = {
    'app':                        '../js/', // 'dist',
    '@angular':                   '../node_modules/@angular',
    'angular2-in-memory-web-api': '../node_modules/angular2-in-memory-web-api',
    'rxjs':                       '../node_modules/rxjs',
    'moment':                     '../node_modules/moment/moment.js',
    "@vaadin/angular2-polymer":   '../node_modules/@vaadin/angular2-polymer'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    '@vaadin/angular2-polymer':   { main: './index.js', defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' }

5) app.module.ts:
import { NgModule, CUSTOM_ELEMENTS_SCHEMA }	from '@angular/core';
...
import { PolymerElement } from '@vaadin/angular2-polymer';
...

@NgModule({
	imports: [ 
...
		 ],
	declarations: [ 
				...
				PolymerElement('vaadin-date-picker'),
                                ...				 
],
	bootstrap: [ AppComponent ],
	schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})

export class AppModule { }

6) In my html template:
`<vaadin-date-picker label="Pick a date"></vaadin-date-picker>`
`<vaadin-date-picker label="Birthday" [(value)]="birthday"></vaadin-date-picker>`

### Browsers Affected

- [ ] Chrome
- [ ] Firefox

**Comment by Saulis** [comment]
Hi!

Can you check if your browser can locate the dependencies under `bower_components` correctly?

**Comment by 25ar** [comment]
Yes, my browser can locate dependencies:
![vaadin1](https://cloud.githubusercontent.com/assets/10981686/19143884/4cfaf34c-8baf-11e6-8145-873f5a23e814.png)
![vaadin2](https://cloud.githubusercontent.com/assets/10981686/19143918/67f8b86e-8baf-11e6-8ab1-ecbb9a43e24c.png)

**Comment by platosha** [comment]
Looks like some Angular dependencies for `angular2-polymer` are missing.

What versions of the angular2-polymer and Angular are you using?

**Comment by 25ar** [comment]
I use:
@vaadin/angular2-polymer@1.0.0-beta5,
@angular 2.0.0-rc.5

**Comment by platosha** [comment]
@25ar there is a mismatch. The v1.0.0-beta5 of @vaadin/angular2-polymer is targeted for Angular 2.0.0.

Please try either to upgrade your project to Angular v2.0.0 at least, or downgrade the @vaadin/angular2-polymer package version to 1.0.0-beta3.

Also, please remove the `node_modules/@vaadin` directory completely before changing any versions, just to ensure that the installation is clean from deep dependencies.

**Comment by 25ar** [comment]
I updated my Angular to 2.0.1 version, datepicker works, but it has broken my router. After i imported PolymerElement in my app.module.ts, everything is in <router-outlet></router-outlet></content> doesn't apear

**Comment by platosha** [comment]
Well, that’s another issue.

Take a look at https://github.com/vaadin/angular2-polymer-quickstart project. It uses Angular 2.0.0 with router, Polymer and Vaadin Elements as well.

If it doesn't help, please file another issue in the https://github.com/vaadin/angular2-polymer repo. This is most likely the support package issue, not in the `<vaadin-date-picker>` element itself.

**Comment by 25ar** [comment]
Thanks a lot. The problem was with my wrapper over `<router-outlet></router-outlet>`.
