### ISSUE TITLE
Improve UX of week numbers

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-date-picker#253]
Currently the date picker week numbers have some UX issue. They are equally close from two weeks. It’s not clear which week do they correspond to.

**Comment by jouni** [comment]
I’ll provide an updated design mockup.

**Comment by jouni** [comment]
We actually had this designed already by Tuomas. Some parts of the design have changed since, but you can use the week number design from this mockup: https://drive.google.com/file/d/0BzkWbWvgmkIxUlBlWDZRNHF1OWs/view
