### ISSUE TITLE
vaadin-date-picker lists year 0

### ISSUE THREAD

**Issue by istvanszoboszlai** [vaadin/vaadin-date-picker#254]
### Description

`vaadin-date-picker` element lists year 0, which does not exist in Gregorian calendar. See: https://en.wikipedia.org/wiki/0_(year) 
### Proposed fix

Year 1 should be after year -1, or even better year 1 BC.
Mayben even better UX would be to display all years padded to 4 zeros, like 0001 and 0001 BC.
### Steps to reproduce
1. Put a `vaadin-date-picker` element in the page.
2. Open the page in a web browser.
3. Click the input of `vaadin-date-picker` element.
4. Scroll to year 0. It is there :)
### Browsers Affected

not browser specific (only tested in latest chrome and firefox)

**Comment by Saulis** [comment]
Just out of curiosity, what's the use case you're having issues with?

**Comment by manolo** [comment]
ISO 8601 uses astronomical year numbering, meaning year 0 = 1 BC, year -1 = 2 BCE.
JavaScript date, which is the object we rely on uses the same system, so this is valid `d = new Date(); d.setFullYear(0); d.toDateString();` -> `"Sat Oct 14 0000"` 
Just for information the native `<input type="date">` does not list years BC, they just start on 1.

**Comment by istvanszoboszlai** [comment]
@Saulis, no specific use case :)
I just liked how the calendar scrolls and I scrolled all the way up to 0. Then I noticed the issue.
