### ISSUE TITLE
Space between months are pretty uneven

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-date-picker#258]
### Description

`<vaadin-month-calendar>`'s parent has height set to `250px`. This does not take consider on how many rows of dates the month actually has. This creates uneven margins between months.

![vaadin_month_margin](https://cloud.githubusercontent.com/assets/8615573/19348863/ad6942a2-9158-11e6-9f96-177500c725ee.PNG)

**Comment by tomivirkki** [comment]
No longer an issue with the latest design/version

**Comment by jouni** [comment]
Well, the issue is still that some months contain fewer weeks than others, so we always have to reserve the same space for all months. Though, that is just fine at the moment.
