### ISSUE TITLE
Today can be focused even when outside min and max range.

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-date-picker#261]
### Description
Today can be focused even when outside min and max range.

### Expected outcome
That's a really good question :-) I'm pretty sure nothing should be focused, but there date-picker should be still scrolled somewhere feasible.

"Today" button should be disabled.

### Actual outcome
date-picker is scrolled to Today it gets focused, but user can't move the focus anywhere with arrows. 

Additionally, when focus is on the valid area, pressing "Today" will move the focus to today.

### Live Demo
https://jsbin.com/kajujiyopo/edit?html,output

### Steps to reproduce
Open zhe pickah and witness the horror!

### Browsers Affected
All

**Comment by Saulis** [comment]
ping @jouni

**Comment by platosha** [comment]
Disabling today button was added in #264.

The initial position part of the issue can be solved by specifying `initialPosition` property.

I suppose there is nothing to enhance, except suggesting to also specify `initialPosition` when setting limits in the documentation.

**Comment by jouni** [comment]
Talked with @tomivirkki about this, and we decided that we should adjust the default initial position so that it’s always inside the valid range, closest to today. If the developer specifies the initial position explicitly, we don’t touch it.

**Comment by tomivirkki** [comment]
There's an issue for this at https://github.com/vaadin/vaadin-date-picker/issues/272
