### ISSUE TITLE
Why fix the vaadin-date-picker "iron-dropdown" with top:0px? 

### ISSUE THREAD

**Issue by ybarbaria** [vaadin/vaadin-date-picker#266]
There are any way to fix the iron-dropdown near of the vaadin-date-pricker instead of the top of the page? 

Thx 

Yvan

**Comment by platosha** [comment]
I can not understand your question. Could you, please, specify, which browsers and devices are affected? Screenshots and live demos could be helpful too.

**Comment by samiheikki** [comment]
Closing this issue. @ybarbaria please re-open if something is still unresolved.
