### ISSUE TITLE
Add styling mixins for the overlay buttons

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-date-picker#271]
Users should be able to apply CSS rules for the following elements and states:
- the cancel button
- the today button
  - default state, selects today and closes the overlay
  - scrolling state, scrolls to today instead of selecting it (2 states):
    - today is before the current visible dates
    - today is after the current visible dates
  - disabled state, does nothing

**Comment by jouni** [comment]
The new Polymer 2 version, with `ThemableMixin` solves the main issue described here. The different states for the Today button remain, but I’m no longer considering those as a requirement.
