### ISSUE TITLE
Date Picker allows typing whatever stuff in the text input

### ISSUE THREAD

**Issue by manfield** [vaadin/vaadin-date-picker#282]
### Description
Close the date picker, using the calendar icon.

### Expected outcome
Input text should show the selected date.

### Actual outcome
Text input becomes "writable".
You can then write whatever string. Validation seems to be bypassed:

http://screencast.com/t/gyN42wA09Suf

### Live Demo
You can replicate in your live demo.

Check the video: http://screencast.com/t/buLDpB6XiO

### Browsers Affected

- [ X] Chrome
- [ X] Firefox
- [X ] Safari
- [ ] Edge - not tested
- [ ] IE 11 - not tested
- [ ] iOS Safari - not tested
- [ ] Android Chrome - not tested

**Comment by tomivirkki** [comment]
Hi @manfield,
This indeed was a bug in `vaadin-date-picker` versions before 1.2.0. The soon to be released 1.2.0. version introduces keyboard input feature that allows the user to type into the input field for date selection. An invalid input is considered as error in validation also.

You can already try out the new feature with [v1.2.0-alpha2](https://github.com/vaadin/vaadin-date-picker/releases/tag/v1.2.0-alpha2) release.
