### ISSUE TITLE
vaadin-infinitite-scroller style element is outside the template element. 

### ISSUE THREAD

**Issue by JockeCK** [vaadin/vaadin-date-picker#286]
### Description
The styling breaks the polymer rules on styling. 

"Scoped styles should be provided via <style> tags placed inside the element's local DOM <template>."

However this is not so in "vaadin-infinitite-scroller.html".

Source: https://www.polymer-project.org/1.0/docs/devguide/styling

### Expected outcome
That style rules such as #scroller stay local.

### Actual outcome
Style rules such as #scroller "leaks" out to other places. 

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Safari
- [ x] Edge
- [ x] IE 11
- [ x] iOS Safari
- [ x] Android Chrome

**Comment by tomivirkki** [comment]
Thanks for the report @JockeCK. Created PR https://github.com/vaadin/vaadin-date-picker/pull/287 to fix this.
