### ISSUE TITLE
Missing label  place-holder or display label as default paper-input elements

### ISSUE THREAD

**Issue by ixchelruiz** [vaadin/vaadin-date-picker#290]
### Description
I'm using paper-input default behavior on my form  ( having the label as a place holder until the user types ). Date-picker label is always floating

### Expected outcome
Seamless behavior with paper-input component

### Actual outcome
Date-picker label is always floating

### Live Demo
add place-holder property

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [x ] Safari
- [ x] Edge
- [x ] IE 11
- [ x] iOS Safari
- [ x] Android Chrome

**Comment by Saulis** [comment]
Hi there!

We're going to address this issue in #269, so I'm going to close this ticket as duplicate.
