### ISSUE TITLE
Implement UX changes for 1.2 final

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#291]
- Esc should work as 'cancel'
- Today/Cancel buttons should be focusable with tab
- Mousedown should focus a date
- Focus should be indicated with proper theming
- Should not focus/select the input text while navigating with arrows
- Right/left arrows should also move focus to overlay iff input field is empty

**Comment by jouni** [comment]
Hopefully we can close this today, and release the first beta.
