### ISSUE TITLE
Create MVP

### ISSUE THREAD

**Issue by wolfie** [vaadin/vaadin-date-picker#3]
MVP Features
---
- [x] Month calendar view.
- [x] Allow navigation between months.
- [x] Allow picking a date from the month calendar (mouse/touch).
- [x] Allow clearing of the selected value.
- [x] Scroll to the selected date in month view when opening (current day by default).
- [x] Allow two-way Polymer data-binding (`value-changed` event).
- [x] Locale for the MVP is fixed to en-us.
- [ ] Asciidoc documentation

**Comment by jounik** [comment]
Would you mind adding a target for the locale, as the target is not clear at the moment. I’m guessing the target is en-us.
