### ISSUE TITLE
Unclear state after deselecting with space

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-date-picker#302]
### Description
If a date picker is empty, and you open the popup then today's date is indicated so you know where you start navigating from using the keyboard.

If a date picker is empty, you open the popup and select a date using space and then deselect it using space (which I find overall to be an unexpected feature) you are left in a state where no date is indicated, no is selected and you have very little information about what is going to happen when you continue navigating.

**Comment by Saulis** [comment]
Totally agree, I think we need to consider separating the `selected` and `focused` dates when navigating. More concretely, focus is always visible and doesn't disappear when the selected date is deselected.

**Comment by tomivirkki** [comment]
We kind of took the opposite direction with this and decided not to highlight the selected date at all (as before) by default.

Selecting the date with space was discussed also and it should be considered a 'deprecated feature' now. Could we drop it completely during the beta period @jouni?

**Comment by jouni** [comment]
Well, that surely is confusing behavior. I would not expect to be able to clear the value (or “deselect” to be more precise) with the space key.

I’m leaning more towards Tomi’s suggestion, but perhaps just so that we allow selecting with space, but not “deselecting/clearing”

**Comment by jouni** [comment]
Not 100% sure if there are any caveats with using space to select. Now that it doesn’t close the overlay (when selecting with space), it allows for certain use cases if you want to change the date quickly multiple times between adjacent dates.

**Comment by jouni** [comment]
Just to add, this “deselect using space” behavior is something which was never planned or designed, I believe.

**Comment by Saulis** [comment]
Can't remember the origin either, but it is mentioned in the WAI ARIA authoring practices, which I believe we should follow: https://www.w3.org/TR/wai-aria-practices/#datepicker

**Comment by jouni** [comment]
Right, that’s correct. In that case, I agree, we should keep the behavior.

Would it be more expected to close the overlay also when selecting with space?

**Comment by jouni** [comment]
Scratch that, that is probably against the aria specs also.

Bugger, I’m disappointed i myself for not considering the aria specs earlier.

**Comment by Saulis** [comment]
I don't see any fundamental problems having the space selection/deselection? 

I guess the main issue with the current behavior is that after deselecting, the focus kinda disappears  - it's reverted back to "today" but there is no visual indicators of that.

**Comment by jouni** [comment]
No fundamental problems, no. Would have been easier just to disable deselection, so there would not be this problematic state where the value is cleared and the focus is lost.

Would it make sense to move the focus back to the input when the value is cleared? That way, we could restore the focus style for the today cell, and keyboard navigation would still work as expected (left/right/up/down arrow keys all navigate the overlay if you do not type anything).

**Comment by Saulis** [comment]
As we don't currently "blur" the input (it has the blue underline always) it's not visually that explicit when the focus is moved over the the input. I think we would need to fix that if we would go ahead and move the focus to the input on deselect.

However, as a user I would expect the keyboard focus stay where it is regardless of if I'm selecting/deselecting a date?

**Comment by jouni** [comment]
Here’s my first proposal: add an additional style for the case when the overlay has focus, but no date is pre-selected.

![date-picker-keyboard-nav-styles](https://cloud.githubusercontent.com/assets/66382/20625585/ed31105a-b31c-11e6-9e4c-9ea0a822d791.png)

**Comment by Saulis** [comment]
Looks good – so after a deselection is done with `space`, the expected behaviour would be that focus stays in the same date and hitting space again will re-select it?

**Comment by jouni** [comment]
@Saulis right

**Comment by jouni** [comment]
Just to clarify for future reference, we concluded after a live chat that just adding a new style for the currently selected day is enough to clarfy this edge case for now.
