### ISSUE TITLE
Focus animation is run when overlay is opened

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#304]
### Description
The paper-input focus animation is run again when the overlay is opened.

### Expected outcome
Focus style stays, but the animation is not run.

### Actual outcome
Focus animation is run again, which causes unnecessary blinking.

### Live Demo
http://artur.app.fi/date-picker/

### Steps to reproduce
1. Focus the date picker with the tab key
2. Press arrow down → focus underline is animated

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari

**Comment by Saulis** [comment]
Currently, `<iron-dropdown>` will moves focus to its child element after the overlay has been opened, then focus is moved back to the input explicitly causing the blinking – we need to set `no-auto-focus` to prevent overlay from getting a focus in the middle.
