### ISSUE TITLE
i18n options optional

### ISSUE THREAD

**Issue by CLEMARCx** [vaadin/vaadin-date-picker#307]
Hi there,

maybe I'm doing sth wrong, but when I want to set a custom date format via i18n and formatDate / parseDate, I always have to set all other config optiosn like monthNames, even if I use the default values.

Can this behavior can be changed, so it will use default values, if you dont set the option?

Regards

**Comment by tomivirkki** [comment]
Hi @CLEMARCx,
You don't need to replace the whole `i18n` object if you just want to change the formatter/parser. The best way to change a sub-property is trough Polymer's `set`API:
```
datepicker.set('i18n.formatDate', function(d) {
  // return formatted date
});
```

**Comment by CLEMARCx** [comment]
Hi @tomivirkki,

sorry I forgot to mention, that I'm using the date-picker with angular2. Can I use the Polymer API there aswell?

**Comment by tomivirkki** [comment]
Should work even when used with angular2.

`datepicker.i18n.formatDate = function(){...}` is also ok but it doesn't automatically invoke internal observers (might not be a problem in formatter/parser case)

**Comment by tomivirkki** [comment]
Closing this for now. Please let us know if there is an issue.
