### ISSUE TITLE
Missing 'no-label-float' property like in vaadin-combo-box 

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-date-picker#314]
Starting to use the vaadin-date-picker today i recognized that it is missing the 'no-label-float' property for hiding the float label placeholder.

As your vaadin-combo-box has the 'no-label-float' property, it would be just stringent if all your input controls would feature it.

**Comment by Saulis** [comment]
Thanks for the request!

We've deliberately tried not to couple ourselves with the `<paper-input>` API in case we move away from, but we'll definitely consider this.

Meanwhile as a workaround, you can use `<vaadin-combo-box-light>` to apply a `<paper-input>` which you can fully control: https://cdn.vaadin.com/vaadin-components/master/vaadin-combo-box/demo/advanced.html

**Comment by Skemeth** [comment]
I don't get your explanation Saulis. Could you detail a little bit more the proceedure?

this said, I agree we definitely need a 'no-label-float'

**Comment by Saulis** [comment]
Hi @Skemeth!

We're currently working on making our own input element, namely [`<vaadin-input>`](github.com/vaadin/vaadin-input) – the idea behind having an input with similar features that `<paper-input>` has, but with more flexibility on the theming side.

As `no-label-float` and other floating label related properties in `<paper-input>` are only related to Material Design, `<vaadin-input>` won't have those properties, but instead, we'll try to implement a way which allows you to have a similar floating label with a themed `<vaadin-input>` using CSS.

So, in the likely event of replacing the default input field in `<vaadin-combo-box>` with `<vaadin-input>` all the `<paper-input>` related properties will/would become obsolete. 

That said, however, will be a major upgrade which probably includes API changes in any case, so I'm not saying it would be totally out of the question to add `no-label-float` to `1.x` versions of `<vaadin-combo-box>`.

**Comment by jouni** [comment]
I think this is a wontfix for version 1.x. The workaround of using vaadin-date-picker-light is hopefully enough.

Also, you can achieve the same effect by using the `placeholder` instead of the `label` attribute.

Same applies to v2.0.

If you ever want to do `always-float-label`, that’s going to be more difficult to pull off without resorting to vaadin-date-picker-light. I can’t think of other workarounds or proper solutions right now.
