### ISSUE TITLE
Localising with moment.js results in massive errors

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-date-picker#315]
Like explained in your docs [https://vaadin.com/docs/-/part/elements/vaadin-date-picker/vaadin-date-picker-localization.html](url) the localisation via moment.js is not working and gives massive errors.

Localizing manually like described at top of your docs page, everything is fine. 

Maybe you can have a look at this issue and see if something in moment.js has changed or a change in the date-picker is causing the errors.

**Comment by Saulis** [comment]
Hi!

Looks like the docs example is missing `weekdays: moment.weekdays()`, thanks for the report!
