### ISSUE TITLE
A strange comma is presented in a DateField

### ISSUE THREAD

**Issue by nutteen** [vaadin/vaadin-date-picker#326]
The following code is used to create a date field with Thai locale.
The affect versions that has been tested are: Vaadin 7.x.x, and 8.0.0.beta1.

`DateField dateField = new DateField();`
`dateField.setCaption("Date:");`
`dateField.setLocale(new Locale("th", "TH"));`
`dateField.setValue(LocalDate.now());`

The current date as of the testing is 19/1/2017.

As a result of the test, in the DateField, it displays "19/1/2017," 
There's a strange comma after the year.

**Comment by nutteen** [comment]
1.

**Comment by jouni** [comment]
This issue was moved to vaadin/framework#8303

**Comment by jouni** [comment]
Thanks for the report! I moved the issue to the correct repo, as you are using the Java framework instead of the Polymer web component date picker.
