### ISSUE TITLE
Datepicker doesn't open on `Space` after it was closed by `Esc`

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-date-picker#328]
Linux/Chrome:

![recorded](https://cloud.githubusercontent.com/assets/6059356/22198474/559a718e-e15f-11e6-84a8-f2cb88465f6a.gif)

**Comment by david35chromy** [comment]
Hi

**Comment by limonte** [comment]
This was fixed after replacing `parer-input` with `vaadin-text-field`.
