### ISSUE TITLE
How can I set datetime to vaadin date picker in full format like "2015-01-01:T05:00:00"?

### ISSUE THREAD

**Issue by TakhirMamirov** [vaadin/vaadin-date-picker#346]
I've tried to set the full datetime repsesentation to vaadin date picker, but seems it doesn't work and don't display the correct date. Actually I don't care about time, but also don't want to transfer datetime back and forth to date only.

**Comment by tomivirkki** [comment]
Just like `<input type="date">`, `<vaadin-date-picker>` only handles date resolution and thus only accepts the following documented formats for `value` https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker-behavior.html#L33

**Comment by goatandsheep** [comment]
We're using `<paper-input type="datetime-local">` for our full date picker
