### ISSUE TITLE
Dates do not get shown after polymer build

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#351]
**Version**: 1.2.2
After a build, the actual dates are not visible to the end user:

<img width="425" alt="screen shot 2017-04-11 at 2 52 31 pm" src="https://cloud.githubusercontent.com/assets/883698/24925586/b521196a-1ec6-11e7-87de-00c2850ab5c0.png">

The app is built with polymer-cli@next with the following build options:
```
"builds": [{
    "name": "bundled",
    "addServiceWorker": true,
    "bundle": true,
    "js": {
      "compile": true,
      "minify": true
    },
    "css": {
      "minify": true
    },
    "html": {
      "minify": true
    }
  }]
```

**Comment by manolo** [comment]
I have not found the error yet, but it's in the JS minimizer. Remove the second line in the "js" block as a workaround right now. I'll continue investigating tomorrow

**Comment by manolo** [comment]
@vaadin-marcus can you please try your examples with vaadin-date-picker#fix/minimizer

polymer minimizer is so aggressive with false. Using null as date objects that are passed from element to element using declarative html are messed up. The same when it removes else clauses returning false.

**Comment by andrewspy** [comment]
@manolo I have same issue, and I am glad to report that vaadin-date-picker#fix/minimizer works for me.
