### ISSUE TITLE
Date not getting selected in chrome when year is scrolled.

### ISSUE THREAD

**Issue by rakesh-roshan** [vaadin/vaadin-date-picker#354]
### Description
When year is scrolled, the date is not picked in chrome. On Firefox it works fine.

### Expected outcome
Date should be selected when year is scrolled and a date is selected.

### Actual outcome
The UI becomes un responsive.

### Live Demo
https://vaadin.github.io/gwt-polymer-elements/demo/#vaadin/VaadinDatePickerSample

### Steps to reproduce
Just open the widget, scroll year and select date in chrome.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment]
Can’t reproduce in a plain Polymer app. Can you test https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/

So the issue might be Polymer + GWT somehow.

**Comment by rakesh-roshan** [comment]
Yeah in pure polymer it is working fine.

**Comment by tomivirkki** [comment]
Closing, reopen if still relevant
