### ISSUE TITLE
Disable the clear icon on `<vaadin-date-picker>` element

### ISSUE THREAD

**Issue by andrewspy** [vaadin/vaadin-date-picker#362]
Is there anyway to disable the clear icon on `<vaadin-date-picker>` element?

My use case is on mobile device where text input are discouraged and the date will always have a pre-defined value and it's a required field.

**Comment by jouni** [comment]
One option is to use vaadin-date-picker light and provide your own paper-input inside which doesn’t have the clear button.

**Comment by limonte** [comment]
Here's the `vaadin-date-picker-light` usage example: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/advanced.html#custom-inputs

**Comment by andrewspy** [comment]
Thanks for suggesting on the `vaadin-date-picker-light` element, but wouldn't it be more logical that the clear icon be removed altogether whenever the `required` attribute is set?

**Comment by jouni** [comment]
Yes, that has come across as a suggestion before also. We’ll be replacing the internal paper-input with [vaadin-text-field](https://github.com/vaadin/vaadin-text-field) in the next major version, and we could cover this issue with a feature in that element instead. In fact, I opened a new issue for it there: https://github.com/vaadin/vaadin-text-field/issues/92

@andrewspy, would you prefer that a required field never has the clear button, or would you prefer that there’s a separate property for controlling it?

**Comment by andrewspy** [comment]
@jouni I would prefer to have a seperate property to enable the clear icon.

The reason being that I can see a use case for the clear icon to be there when the input is a text field(i.e. keyboard input), where the clear icon is there to clear the text value even though the field is `required`.

However if the text field is in `readOnly` (i.e. such as mobile device, where text input is discouraged), the clear icon shouldn't be there when it is `required`.

**Comment by jouni** [comment]
I prefer a separate property as well, and I think a CSS custom property would be a natural choice for this. Something like `--vaadin-combo-box-clear-button-visiblity: visible/hidden;`.

**Comment by andrewspy** [comment]
@jouni Actually, I do not think using CSS custom property is a good idea, as CSS mixin is meant for styling by design (i.e. v.s. functional by design).

I do propese to have a attribute/properties called `no-clear-button` to disable the clear button, much like `no-label-float` for `<paper-input>`. i.e.

```html
<vaadin-date-picker
  no-clear-button>
</vaadin-date-picker>
```

**Comment by jouni** [comment]
I’m not proposing a CSS mixin, just a single property, as we are moving away from using CSS mixins. After we introduce the new styling/theming functionality, we could expose the clear button as a stylable part as well.

The reason for proposing a CSS based solution is that IE/Edge already has this feature for the native input element: https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear

As the icon should be customizable with CSS, it feels like this requirement could be fulfilled by this same functionality, and we shouldn’t introduce extra API for it.

**Comment by andrewspy** [comment]
@jouni I guess it's just a matter of preference. I am just thinking from the user experience (as a developer) perspective that using `no-clear-button` attribute is a much cleaner and concise way to express/consume the API.

I am okay with any implementation. That's just my 2c.

**Comment by jouni** [comment]
Yeah, an attribute/property is probably more useful, as this is something you usually want to do for individual fields only, not for all fields. So I’m not saying CSS is the correct solution for this, it was just my knee-jerk reaction as IE/Edge has this control in CSS.

So perhaps we could implement this as a CSS custom property, but provide a built-in attribute for applying the correct styles. That would allow the developer to hide them from all fields on a page or in a form easily with CSS, or just from individual fields using the attribute (maybe even with data-binding).

Something like this:

CSS in vaadin-date-picker:
```css
#clear {
  /* Using display instead of visibility so that the element doesn’t reserve space when it’s hidden */
  display: var(--vaadin-date-picker-clear-button-display);
}

:host([no-clear-button]) #clear {
  display: none;
}
```

Using:
```html
<!-- Hide for all fields -->
<style>
  vaadin-date-picker {
    --vaadin-date-picker-clear-button-display: none;
  }
</style>

<!-- Hide for an individual field -->
<vaadin-date-picker no-clear-button></vaadin-date-picker>
```

**Comment by jouni** [comment]
Eventually, this feature should be moved to vaadin-text-field, as we are using that internally now instead of paper-input. There’s already a relevant issue there: https://github.com/vaadin/vaadin-text-field/issues/92

**Comment by garcus** [comment]
Same should go for the calendar icon. I can't find a clean way to hide that icon. Using the mixin `--vaadin-date-picker-calendar-icon` and putting `display:none` hides the icon but not the surrounding div that takes up the space. Since the clear icon appears before the calendar icon (2.x) it leaves the clear icon misplaced before the hidden (but "space-allocated") calendar icon.

**Comment by web-padawan** [comment]
Clear button is now hidden by default and can be shown by setting `clear-button-visible` attribute.
This change was released at https://github.com/vaadin/vaadin-date-picker/releases/tag/v4.0.0
