### ISSUE TITLE
'Pointer' cursor is shown despite readonly attribute

### ISSUE THREAD

**Issue by craPkit** [vaadin/vaadin-date-picker#363]
### Description
The contained `paper-input` of the `vaadin-date-picker` element shows the _pointer_ cursor on hover when _readonly_, even though there is no way to interact with it (apart from selecting the text content).

### Expected outcome
The hover cursor should switch to _default_ or _text_ when the `vaadin-date-picker`'s _readonly_-attribute is set to _true_.

### Actual outcome
The hover cursor remains a _pointer_, even when the `vaadin-date-picker` is set to _readonly_.

### Live Demo
https://jsbin.com/jujavarasa/1/edit?html,output

### Steps to reproduce
1. Put a `vaadin-date-picker` element in the page, adding the readonly attribute and, optionally, a value.
2. Open the page in a web browser.
3. Hover over the input of `vaadin-date-picker` element.

### Browsers Affected
- [ x ] Chrome
(no others were tested)

This is remotely related to: https://github.com/vaadin/vaadin-date-picker/issues/201

**Comment by limonte** [comment]
Agree, thanks @craPkit for submitting this small detail! 

@jouni what do you think?

**Comment by jouni** [comment]
Yeah, good catch, I agree.

**Comment by web-padawan** [comment]
This is no longer an issue starting from the 2.0 release which dropped internal Paper Input. The `readonly` text field now uses `cursor: text` indicating that user still can select and copy value.

@jouni is this something that we still want to fix for 1.x branch or we can close?

**Comment by jouni** [comment]
Not a big priority, in my opinion. Is this btw a paper-input “feature” or have we introduced the cursor style?

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
