### ISSUE TITLE
date-picker scrolls while scrolling the window on Chrome

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-date-picker#364]
### Description
vaadin-date-picker scrolls while scrolling the window on Chrome

### Expected outcome
When scrolling the window, date-picker should not scroll.

### Actual outcome
![chrome-date-picker](https://cloud.githubusercontent.com/assets/1039468/25808338/78541ce2-3412-11e7-9dd0-f0a4d5abc934.gif)

### Live Demo
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/

### Steps to reproduce
1. Open date-picker
2. Scroll the window
3. Witness the horror!

### Browsers Affected
At least Chrome 58 on MacOS, Safari works just fine.

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
