### ISSUE TITLE
Incorrect date format when using `i18n.formatDate` in `value` attribute

### ISSUE THREAD

**Issue by andrewspy** [vaadin/vaadin-date-picker#365]
### Description
`vaadin-date-picker` element does not format the date correctly in `value` attribute using `i18n.formatDate`.

### Expected outcome
`value` should be formatted according to the `i18n.formatDate`.

### Actual outcome
It always display `M/D/YYYY` format (i.e instead of custom format say `D/M/YYYY`). All formatting is working correctly after a date is selected from the date-picker.

### Live Demo
N/A

### Steps to reproduce
Sample snippet below (assuming custom date format of `D/M/YYYY`):-

```html
<vaadin-date-picker id="dp"
  value="2017-12-31"
  label="Date">
</vaadin-date-picker>
```

```js
{ // Format date-picker
  this.$.dp.i18n.formatDate = function(d) {
    return moment(d).format('D/M/YYYY');
  };
  this.$.dp.i18n.parseDate = function(str) {
    return moment(str, 'D/M/YYYY').toDate();
  };
}
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by tomivirkki** [comment]
Hi @andrewspy

Sorry for the delay. The `formatDate` and `parseDate` functions are there only to allow different visual representation for a date value.

The date picker’s `value` property always reflects the selected date in ISO 8601 format (YYYY-MM-DD), just like in case of `<input type="date">`, and cannot be changed.

**Comment by andrewspy** [comment]
@tomivirkki I think you have mis-understood me. I am having problem on the visual representation in displaying in `D/M/YYYY`, which always default to display in `M/D/YYYY` despite properly setting `i18n.formatDate` and `i18n.parseDate` properly in Polymer's `ready()`.

```html
<vaadin-date-picker id="dp"
  value="2017-12-31"
  label="Date">
</vaadin-date-picker>
```

The above code shoud show `31/12/2017`, but it show `12/31/2017` instead.

**Comment by platosha** [comment]
@andrewspy could you please try using the Polymer’s `set` method? Example based on your snippet:

```javascript
  this.$.dp.set('i18n.formatDate', function(d) {
    return moment(d).format('D/M/YYYY');
  });
  this.$.dp.set('i18n.parseDate', function(str) {
    return moment(str, 'D/M/YYYY').toDate();
  });
```

**Comment by andrewspy** [comment]
@platosha Using Polymer's `set` method does seem to fix the issue, thanks for the workaround!

Being said that, custom element should be modular by itself, and shoud not depend on Polymer, I shall close the issue for now and leave that to vaadin's team. Thanks again!
