### ISSUE TITLE
vaadin-date-picker-light freezes

### ISSUE THREAD

**Issue by jacsbro** [vaadin/vaadin-date-picker#377]
### Description
Our users are often searching for data in the last century and do not want to scroll around in the date-picker to find the date in question. They just want to type in e.g. 1950 to jump to 1/1/1950 and select 
a date from there. We know that this all works out of the box with vaadin-date-pciker - but our users 
are confused by the calender poping up as soon as they enter the text field. So the requirement is:

- do not show the calender on focus of the textfield
- open/close the calender by clicking on the icon (it's ok for the calender to popup after the user starts typing)

As we did not see support in vaadin-date-picker for this we gave vaadin-date-picker-light a try which looked
promising on the first glance. Unfortunately we are facing 2 problems with it:

1.) the calender does not close when invoking the close() function (triggered when clicking on the icon)
2.) if you click on the icon multiple times the complete gui freezes. we need to relaod the page and start over again.   this is currently a showstopper for us.

### Expected outcome
1.) close the calendar when clicking on the icon (after it was opened)
2.) do not freeze the gui

### Actual outcome
1.) does not close
2.) freezes after clicking on the event icons multiple times.

### Live Demo
http://jsbin.com/ravojex/edit?html,output
We noticed that this jsbin seems to work with chrome only. Outside of jsbin we see the calendar on the browsers listed below

### Steps to reproduce
see above

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari (not tested)
- [ ] Edge (not tested)
- [x] IE 11
- [ ] iOS Safari  (not tested)
- [ ] Android Chrome  (not tested)

Hint: Please note, that we cannot use Polymer2 and need to stick to the v1.2.3 version.

**Comment by samiheikki** [comment]
Hi @jacsbro Have you tried out moving the icon outside of the `<vaadin-date-picker-light>`? Like this: http://jsbin.com/manetowonu/1/edit?html,output

**Comment by jacsbro** [comment]
Thanks for the hint @samiheikki - the jsbin seems to work now! I'll try tomorrow more in detail when back in the office. 

Just for curiosity - why should the icon be outside the component? The "check-in" demo on https://vaadin.com/elements/-/element/vaadin-date-picker#demos places the icon inside the component as well.

**Comment by samiheikki** [comment]
That is true. Will also work fine if you put icon back inside the tag, but remove the `on-tap="_calendarClick"` from it.

**Comment by samiheikki** [comment]
Hi @jacsbro Did it work? OK to close this issue?

**Comment by jacsbro** [comment]
Dear @samiheikki - I did not find the time to investigate... I'll close it if it works. Is that ok for you?

**Comment by samiheikki** [comment]
Sure, thanks for the reply!

**Comment by jacsbro** [comment]
Hi @samiheikki - it works now as expected. Thanks again for your great support! 

Have a nice weekend.

**Comment by samiheikki** [comment]
Awesome! Have a nice weekend!
