### ISSUE TITLE
2.0 Error messages are not showing

### ISSUE THREAD

**Issue by H3dz** [vaadin/vaadin-date-picker#378]
### Description
Setting an error message will not display the paper-input-error.

### Actual outcome
The field is marked as invalid, but the text is not visible.

### Fix
paper-input-error is missing the slot attribute
`<paper-input-error aria-live="assertive" slot="add-on">[[errorMessage]]</paper-input-error>`

**Comment by tomivirkki** [comment]
This should be ok in the current master. Notice that we're in the process of replacing the internal Paper elements with `<vaadin-text-field>` and `<vaadin-button>`. This means that 2.0.0 stable will most likely not be a hybrid / include Paper elements at all.
