### ISSUE TITLE
Could not find style data in module named vaadin-button-default-theme

### ISSUE THREAD

**Issue by rkief** [vaadin/vaadin-date-picker#381]
### Description
After upgrading from v2.0.0-alpha1 to v2.0.0-alpha2, there is this warning:
"Could not find style data in module named vaadin-button-default-theme"

Date-picker has lost its style.
### Expected outcome
Date picker would look the same after upgrade.

### Actual outcome
![alpha2](https://user-images.githubusercontent.com/6942327/26849195-3ba33744-4ad1-11e7-88e2-0314af4861f5.PNG)
![alpha1](https://user-images.githubusercontent.com/6942327/26849196-3ba6e1d2-4ad1-11e7-8e92-ceee01d8db8b.PNG)

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
We’re gradually replacing Paper elements with Vaadin elements in our components and in date picker’s case this was done in [2.0.0-alpha2](https://github.com/vaadin/vaadin-date-picker/releases/tag/v2.0.0-alpha2) phase.

If you need a Material date picker with Polymer 2 right now, I suggest sticking with the alpha1 version for a while. Sometime in the near future, we’ll release [vaadin-material](https://github.com/vaadin/vaadin-themes/tree/master/material) theme bundle that will, when imported to a page with Vaadin elements in it, decorate the elements with Material appearance.

**Comment by jouni** [comment]
Update: if you want to use a newer version, you can now install [vaadin-theme](https://github.com/vaadin/vaadin-themes) and use the Material theme for date picker from there.

**Comment by jouni** [comment]
Also, I think the error message is now gone as vaadin-button has an empty default theme implementation.
