### ISSUE TITLE
Year numbers misaligned on Firefox (2.0.0-alpha2) when scrollbars visible

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-date-picker#384]
![screen shot 2017-06-08 at 12 56 38](https://user-images.githubusercontent.com/1039468/26923222-25ecee20-4c4a-11e7-8e28-acd8ba0db434.png)

Setting  `width: 90px` (parent width) on the buffer elements seems to help.

**Comment by platosha** [comment]
NB: both scrollers suffer from the same issue. The months are also misaligned, as shown on the screenshot.

`90px` means `scrollerWidth + 40px`, where `40px` is an offset to hide the scrollbar (the same value in both month and year scrollers).

**Comment by tomivirkki** [comment]
The year scroller misalignment was a regression from https://github.com/vaadin/vaadin-date-picker/pull/376/files#diff-3c4a6f179f3619ca53d18b2bd4ec3317L138

Added a PR to restore the removed value
