### ISSUE TITLE
Can you please explain on how to install this on angular4 cli project ?

### ISSUE THREAD

**Issue by hxdef2517** [vaadin/vaadin-date-picker#386]
Can you please explain on how to install this on angular4 cli project ? Is there a way to install it without bower and polymer, but using npm ? and what to include in angular project in order to use a date picker. Thank you

**Comment by jouni** [comment]
Hi! We are not actively supporting Angular. Our elements are not yet published on npm (as Polymer dependencies are not there yet), but eventually they will be. Also Polymer is a required dependency, our elements won’t work without it.

If you want to use our elements with Angular, please take a look at these options that Angular and Polymer play nice together:

- https://github.com/platosha/angular-polymer
- https://github.com/hotforfeature/origami
