### ISSUE TITLE
How can I use it inside a html form?

### ISSUE THREAD

**Issue by PhilAndrew** [vaadin/vaadin-date-picker#388]
how can I use it inside a html form?

I need it to submit a value when the form is submitted.

**Comment by jouni** [comment]
You need to use `<iron-form>` (or `<form is="iron-form">` in Polymer 1). Standard HTML forms won’t be able to read the field value from inside the shadow DOM.

**Comment by PhilAndrew** [comment]
So I cannot use it in a standard html form unless I changed it somehow such as adding an event handler to set a value on a html form right?

**Comment by samiheikki** [comment]
Hi @PhilAndrew Here is a great tutorial on forms with Polymer elements. https://www.youtube.com/watch?v=AVXu1_vaY2U Basically you can use date-picker's `value` property (corresponds to the video's `birthday` property).
