### ISSUE TITLE
Two date pickers side-by-side demo broken

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-date-picker#389]
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/advanced.html#two-date-pickers-side-by-side
Date pickers are not side by side.
<img width="867" alt="screen shot 2017-06-20 at 9 09 08" src="https://user-images.githubusercontent.com/8615573/27319065-4df53dee-5598-11e7-8cc6-4d8a76a7fc70.png">

**Comment by jouni** [comment]
Why is that example even in the “Advanced Usage“ page? I mean, the title is at least not that advanced :)

**Comment by jouni** [comment]
The cause of this issue is probably this error in the console:

> https://cdn.vaadin.com/vaadin-core-elements/master/iron-flex-layout/classes/iron-flex-layout.html Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)

**Comment by samiheikki** [comment]
Better fix for this would be to remove iron-flex classes and just add couple lines of css (not likely that everybody has iron-flex classes installed (just like we don't)).
```
div {
  display: flex;
  justify-content: space-between;
  /* or something similar */
}
```

**Comment by jouni** [comment]
Just remove this example, as it’s quite confusing on mobile devices anyways: the second date picker opens without the users request, and doesn’t contain any context info what date you are choosing (the “End” label is not visible in the fullscreen overlay. This is not an example we want to promote.
