### ISSUE TITLE
Safari Screen-Reader Very Slow

### ISSUE THREAD

**Issue by alogan519** [vaadin/vaadin-date-picker#391]
Safari gets into ‘busy’ mode _every time_ a switch is made into or out of the calendar or on change of dates, and it takes a good 11-12 seconds to get functional again. Is it possible to get addressed as Safari/VoiceOver combination is very prominent among accessible usage?

### Steps to reproduce
https://www.apple.com/voiceover/info/guide/_1124.html

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment]
Seems to be working fine with the latest version. Reopen if still relevant.
