### ISSUE TITLE
Cancel button active state is not cleared

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#392]
Steps to reproduce:

- Open the dropdown
- Focus the Cancel button using the tab key
- Press Enter -> overlay closes
- Open the dropdown again
- Inspect the Cancel button and see that the `active` attribute is still present for the button

**Comment by gatanaso** [comment]
Same issue occurs with the 'Today' button.

**Comment by web-padawan** [comment]
Fixed in vaadin/vaadin-button#65
