### ISSUE TITLE
Problem with fixed width for the inner vaadin-text-field (v2.0.0-beta1)

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-date-picker#400]
### Description
I create a flexbox div that should be 120px wide,  and set the included vaadin-date-picker width to 100%.

### Expected outcome
I expect the vaadin-date-picker to be resized to a width of 120px.

### Actual outcome
The result is that the width is 160px, that widens also the container flexbox, of course, so all the result is misaligned.

Using Chrome Developer Tools I see that there's a vaadin-text-field inside the vaadin-date-picker. In the source code for the vaadin-text-field I see that there are two :host selector, one with fixed width of 160px, and one with fixed width of 175px. I don't think this is correct, but anyway, is there any way to modify these values from my application?
Thanks

**Comment by jouni** [comment]
@limonte, this should be fixed before 2.0 final.

`[part=text-field]` width should be 100%, not min-width: https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L30

Then, the `:host` of `vaadin-date-picker should have the same default width as `vaadin-text-field` (175px): https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L67

**Comment by andreabioli** [comment]
??? :-)

**Comment by samiheikki** [comment]
@andreabioli jouni's comments were addressed to one of our team member as a reminder that we will fix this before releasing 2.0 stable version of vaadin-date-picker.

**Comment by jouni** [comment]
So, was this actually addressed in v2.0 final? @tomivirkki

**Comment by tomivirkki** [comment]
Apparently not https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L30

My PR proposes fixing this by adding `max-width: 100%;` to `[part=text-field]` also. Setting `[part=text-field]`'s width to 100% would override the default magic width so this way we could avoid having to repeat it in date picker. You see some dangers in this approach @jouni ?

**Comment by jouni** [comment]
Sounds like a nice solution to me.
