### ISSUE TITLE
Setting invalid = true has no effect on visualization (v2.0.0-beta1)

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-date-picker#402]
### Description
I'm binding the 'invalid' property to a computed local property, but when the computed property returns false, there's no evidence of the error.

### Expected outcome
The date picker becoming red

### Actual outcome
The date picker remains dark

![image](https://user-images.githubusercontent.com/13900431/28209199-ce39a7fe-6891-11e7-889d-ba87ab7d6461.png)

I've created a computed property that compares two dates (and I show it for test purposes on the screen, as you can see).
When the property becomes true, I see that the 'invalid' attribute is not set at all in the element, as it should be, being the linked property true:
![image](https://user-images.githubusercontent.com/13900431/28209295-2d733bc2-6892-11e7-8f80-a64e869f9d13.png)
This is the source code for the above:
```
...
<vaadin-date-picker id="finStart" value="{{finStart}}" style="width:100%" label="Financial Start Date" invalid="{{finStartInvalid}}"></vaadin-date-picker>
{{finStartInvalid}}
...

```

**Comment by andreabioli** [comment]
I traced source code, and I see that after the property is calculated, during the overlayClosed event, a 'checkValidity' function is called in the mixin, that validates only formally the date inserted, and overrides the value I just passed in setting the 'invalid' property (of course when you select a date, this date is always valid).

**Comment by andreabioli** [comment]
Ok, one solution, that I found on the 'hidden' demo for version 2 Beta, is to derive a class like in the following:

```
<dom-module id="ey-date-picker">
    <script>
        class EyDatePicker extends Vaadin.DatePickerElement {
            static get is() { return 'ey-date-picker'; }

            static get properties() {
                return {
                }
            }

            checkValidity(value) {
                var valid = super.checkValidity();
                debugger; debugger;
                if (valid) {
                    var currentYear = new Date().getFullYear();
                    valid = new Date(value).getFullYear() === currentYear;
                }
                return valid;
            }

        }

        customElements.define(EyDatePicker.is, EyDatePicker);
    </script>
</dom-module>
```
Of course we can customize the checkValidity also in a generic way...
I would like to know it this is the 'official' idea...

**Comment by platosha** [comment]
@andreabioli I think it’s fine to override for `checkValidity` until we have a better idea. API doc instructs to do so, actually: https://github.com/vaadin/vaadin-date-picker/blob/1255b15e53bacc59f03bd0dc86647455166db316/vaadin-date-picker-mixin.html#L601

The same concerns `<vaadin-text-field>` in general, overriding `checkValidity` is a supported way of implementing custom validation, as of now: https://cdn.vaadin.com/vaadin-text-field/1.0.0/demo/validators.html#synchronous-custom-validator

**Comment by andreabioli** [comment]
Good. It's not so easy to find the correct examples to follow, but it's also true that as developers we should be able to scroll quickly through (and understand!) the source code! ;-)
Thank you very much!

**Comment by jouni** [comment]
Should this issue be closed as invalid or wontfix for now?

**Comment by limonte** [comment]
> Good. It's not so easy to find the correct examples to follow, but it's also true that as developers we should be able to scroll quickly through (and understand!) the source code! ;-)

- https://cdn.vaadin.com/vaadin-date-picker/2.0.0-beta2/#/elements/vaadin-date-picker#methods
- https://cdn.vaadin.com/vaadin-date-picker/2.0.0-beta2/demo/advanced.html#custom-validator

**Comment by andreabioli** [comment]
Very good, thanks! I found new ways to look for infos: but were they 'reachable' from the vaadin main web site??? :-)

**Comment by jouni** [comment]
That os true, and unfortunate at the moment. All elements will eventually be there as well (once we get stable versions). The process is not yet fully automated, and there’s no desicated team to update them on the website, so we temd to forget to do that during development 🙄

**Comment by andreabioli** [comment]
I totally appreciate and understand your efforts, and this is in the end a really minor problem.
Thanks!
