### ISSUE TITLE
Airline Datepicker

### ISSUE THREAD

**Issue by vibingopal** [vaadin/vaadin-date-picker#404]
### Description
Hi Team,

Could you please let me know how to implement airline datepicker with custom range using the current component. At this moment unable to select two date in one user action. 
### Expected outcome

Airline calendar date selection with custom input

**Comment by samiheikki** [comment]
Take a look at these examples and you will get it done quite easy:

Two date-pickers:
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/advanced.html#two-date-pickers-side-by-side

custom input:
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/advanced.html#custom-inputs

Range selection:
https://github.com/vaadin/vaadin-date-picker/issues/2#issuecomment-252587703
