### ISSUE TITLE
Days of week names are misaligned

### ISSUE THREAD

**Issue by gatanaso** [vaadin/vaadin-date-picker#408]
### Description

The days of week names of the vaadin-date-picker are misaligned with their respective values:

![day-of-week-misaligned](https://user-images.githubusercontent.com/15094658/28824901-d25d817c-76cc-11e7-92ac-3f4c2cad174a.png)

### Live Demo
https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/

### Steps to reproduce
Open the first calendar of the vaadin-date-picker demo: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/

### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by gatanaso** [comment]
The alignment is okay for the vaadin-date-picker with week numbers:

![okay-aligned](https://user-images.githubusercontent.com/15094658/28825122-a2cdce66-76cd-11e7-9b2a-d34fdf9be2f7.png)

**Comment by samiheikki** [comment]
Probably just due to missing import in the demo page as it is working in the 2.0.0 page (which too points to master at the moment). I'll see if I can refresh the demo pages.
`GET https://cdn.vaadin.com/vaadin-core-elements/master/iron-flex-layout/classes/iron-flex-layout.html 404 ()`.

**Comment by samiheikki** [comment]
Actual issue. Prioritizing this.
