### ISSUE TITLE
The sample jsbin provided at the issue template doesn't load vaadin-date-picker

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-date-picker#412]
### Description

https://jsbin.com/qojiwugino/edit?html,output (the link provided at the issue template) doesn't load the `vaadin-date-picker`:

> polygit.org/vaadin-date-picker+vaadin+master/components/vaadin-date-picker/vaadin-date-picker.html Failed to load resource: the server responded with a status of 500 ()

**Comment by samiheikki** [comment]
Problems is with polygit with Polymer 2 elements it seems. I'll see what I can do. Thanks for the report!

**Comment by web-padawan** [comment]
Fixed by [f6f4923](https://github.com/vaadin/vaadin-date-picker/commit/f6f4923514c7696bf0fe21e12ce53e5254a01eed). Closing.
