### ISSUE TITLE
Field gets refocused after blurring, if it was not empty when focused

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#417]
![datepicker1](https://user-images.githubusercontent.com/66382/29778043-b41dabce-8c16-11e7-8a4d-0287931b127c.gif)

**Comment by vicsstar** [comment]
This is reproducible in Safari; doesn't seem to happen anywhere else.

**Comment by vicsstar** [comment]
@jouni this doesn't seem like the desired behaviour. @manolo showed me in person that other components have a consistent behaviour like what you described.

**Comment by jouni** [comment]
@vicsstar, yeah, we talked about that with Manolo as well, and agreed that focus should remain in the field when the overlay is closed. I wasn’t paying enough attention when doing this issue.

There seemed to be some inconsistency in the behavior (sometimes focus remains, sometimes not), though, which should be fixed.
