### ISSUE TITLE
Behaves differently inside a shadow root

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#419]
### Description
Vaadin date-picker inside shadow root behaves differently on mobile from one that's not.

### Expected outcome
1. Tapping the wrapped text field opens up the overlay
2. Tapping the footer in fullscreen mode doesn't close the overlay

### Actual outcome
1. Tapping the wrapped text field doesn't open the overlay (tapping the calendar icon does)
2. Tapping the footer in fullscreen mode closes the overlay

### Live Demo
https://jsbin.com/cesecariti/edit?html,output

### Steps to reproduce
1. Put a `vaadin-date-picker` element into another element's shadow roow
2. Open the page in a web browser.
3. Tap the input of `vaadin-date-picker` element on a mobile device (Chrome at least)

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by jouni** [comment]
Affects Chrome Canary (63) as reported by a user in Slack.

Tomi, did you have any time to investigate yet?

**Comment by tomivirkki** [comment]
Not yet, moved this to backlog

**Comment by jouni** [comment]
This affects the elements on the new vaadin.com website as well, right?

**Comment by YuriyVaadin** [comment]
The issue seems to be fixed after https://github.com/vaadin/vaadin-date-picker/pull/482
