### ISSUE TITLE
No styles mixins [CRITICAL]

### ISSUE THREAD

**Issue by iSuslov** [vaadin/vaadin-date-picker#430]
Take a look at documentation, it says following mixins are available for styling: 

Custom property | Description | Default
-- | -- | --
--vaadin-date-picker-overlay | Mixin applied to the overlay | {}
--vaadin-date-picker-yearscroller | Mixin applied to the year scroller | {}
--vaadin-date-picker-yearscroller-indicator | Mixin applied to the year scroller indicator | {}
--vaadin-date-picker-calendar-icon | Mixin applied to the calendar icon | {}
--vaadin-date-picker-clear-icon | Mixin applied to the clear icon | {}
--vaadin-date-picker-scrollers-fade | Mixin applied to the scrollers fade element | {}
--vaadin-date-picker-header | Mixin applied to the picker header | {}
--vaadin-date-picker-toolbar | Mixin applied to the picker toolbar | {}
--vaadin-date-picker-toolbar-icon | Mixin applied to the picker toolbar icon | {}
--vaadin-date-picker-footer | Mixin applied to the picker footer | {}
--vaadin-date-picker-calendar | Mixin applied to a month calendar element | {}
--vaadin-date-picker-calendar-title | Mixin applied to a month calendar title | {}
--vaadin-date-picker-calendar-cell | Mixin applied to a month calendar cell | {}
--vaadin-date-picker-calendar-date-cell | Mixin applied to a month calendar date cell | {}
--vaadin-date-picker-calendar-weekday-cell | Mixin applied to a month calendar weekday cell | {}
--vaadin-date-picker-calendar-cell-today | Mixin applied to a month calendar today cell | {}
--vaadin-date-picker-calendar-cell-selected | Mixin applied to a month calendar selected cell | {}
--vaadin-date-picker-calendar-cell-focused | Mixin applied to a month calendar focused cell | {}
--vaadin-date-picker-calendar-cell-today-selected | Mixin applied to a month calendar selected today cell | {}
--vaadin-date-picker-calendar-cell-disabled | Mixin applied to a month calendar disabled cell | {}
--vaadin-date-picker-calendar-weeknumber-cell | Mixin applied to a month calendar weeknumber cell | {}
--vaadin-date-picker-calendar-focused-cell-focused | Mixin applied to a focused month calendar focused cell | {}

**In reality the is NO mixins at all!**

What is the status of #359 ? There is no documentation still.

**Comment by jouni** [comment]
Hi. Where did you look at the documentation? We have a bit of a messy situation right now, we are doing a major update to our website, and the current one contains either old or broken docs. 

For the 2.0 version, you can see the docs here: https://cdn.vaadin.com/vaadin-date-picker/2.0.2/index.html#/elements/vaadin-date-picker

We no longer have mixins for our elements. Instead, we have “shadow parts”. The way to style those is using Polymer style modules. Please watch my presentation from a few weeks back, as it contains most of the relevant info regarding this change: https://www.youtube.com/watch?v=xSnG-mNWhqI
The documentation for this is also still in progress.

**Comment by jouni** [comment]
Also, here’s an example how to do a new theme for the date picker: https://cdn.vaadin.com/vaadin-date-picker/2.0.2/demo/theming.html

**Comment by jouni** [comment]
I’m closing this issue as invalid, as the latest version does not contain any mixins in the documentation: https://github.com/vaadin/vaadin-date-picker/blob/master/vaadin-date-picker.html#L131-L160

But feel free to continue asking more questions here!

**Comment by iSuslov** [comment]
Hi, the documentation I looked in is here: https://vaadin.com/elements/-/element/vaadin-date-picker#docs
which is pretty good indexed by google and you got there after asking google `vaadin-date-picker docs`
But I got you, thanks!

**Comment by jouni** [comment]
Good! I hope we’ll get the new site public next week :)
