### ISSUE TITLE
Focus style is not restored when closing the overlay using ESC

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#433]
Steps to reproduce:
- Focus the text field
- Press TAB to move the keyboard focus to the overlay
- Press ESC to close the overlay
- Focus is moved back to the text field but the visual `[focused]` state is not reapplied

![date-picker-focus](https://user-images.githubusercontent.com/66382/30382252-554f019a-98a7-11e7-8e3f-4b62a1a57624.gif)

**Comment by samiheikki** [comment]
Tested on master branch and on demo site (https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-date-picker/demo/#date-picker-basic-demos) on all browsers. This issue seems to be fixed. @jouni can you check and close if works for you too.

**Comment by jouni** [comment]
Yes, seems to be fixed already :+1:
