### ISSUE TITLE
Read-only attribute is not propagated to the internal vaadin-text-field

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#444]
Themes usually make the read-only text-field look different from the normal state, but this bug prevents that from working as expected for the date picker.

**Comment by samiheikki** [comment]
I guess it propagates already: https://github.com/vaadin/vaadin-date-picker/blame/master/vaadin-date-picker.html#L77

**Comment by jouni** [comment]
It binds to the property and not the attribute (and the property is not reflected by text field), which doesn’t work with themes that rely on the state attributes. You can compare the styles of a [read-only text-field](https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha4/demo/text-fields.html#states) and a [read-only date-picker](https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha4/demo/date-pickers.html#states) (the focused state is different).

**Comment by vicsstar** [comment]
@jouni which is the most preferred state here? The one with a highlight or the one without?

**Comment by jouni** [comment]
One without. The text-field has the theme defined (and is the source of truth), and date picker (and combo box as well) just use that internally.
