### ISSUE TITLE
[NFR] Allow value to be set with a Date object

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-date-picker#446]
Allowing a user to set `value` as a standard `Date` object would make programatic work with the element _MUCH_ easier. When working with JS, setting a `value` can get rather cumbersome as there are no built-in methods that output strictly the ISO 8601 date segment. Right now I'm having to do something like:
```
datePicker.value = new Date().toISOString().split('T')[0];
```
to set the default in browser.

**Comment by manolo** [comment]
We are not going to give the user a way to set dates to avoid time problems, see #446.

**Comment by jouni** [comment]
@manolo, you probably meant to link to some other issue than this same one 😊

**Comment by manolo** [comment]
yep,  discussion is in in #449, updated comment.
