### ISSUE TITLE
Unable to select date in Chrome Version 62.0.3202.75 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by atomike** [vaadin/vaadin-date-picker#458]
### Description
Opens Calendar, but clicking on dates does not select the date.

### Expected outcome
Selected date should appear in input box

### Actual outcome
No date selected

### Live Demo
https://vaadin.com/elements/vaadin-date-picker/html-examples/date-picker-basic-demos

### Steps to reproduce
1. Use Chrome Version 62.0.3202.75 (Official Build) (64-bit) 
2. Open https://vaadin.com/elements/vaadin-date-picker/html-examples/date-picker-basic-demos
3. Click any data field
4. Select a date

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [X] Android Chrome

**Comment by tomivirkki** [comment]
Hi, the latest version should have this fixed already: https://github.com/vaadin/vaadin-date-picker/releases/tag/v2.0.6

Looks like the vaadin.com website is still using an outdated version

**Comment by web-padawan** [comment]
vaadin.com now uses the `2.0.7` version where this bug is fixed, so I'm closing this issue.
