### ISSUE TITLE
date-picker does not have a tabindex to make it focusable

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-date-picker#476]
Main issue is that tabindex does not work correctly, and you cannot focus a vaadin-date-picker in a vaadin-dialog

Solution might be extend vaadin-control-state so as it's aligned with other vaadin form elements

**Comment by tomivirkki** [comment]
This is fixed right? @manolo

**Comment by web-padawan** [comment]
Fixed by #478 

note: it seems that in order to target several issues by PR, each of them needs "fixes" or "closes" keyword, otherwise only the first one gets closed after merge (this is what happened here).
