### ISSUE TITLE
Revalidation fails after entering invalid string

### ISSUE THREAD

**Issue by schrotie** [vaadin/vaadin-date-picker#483]
### Description
Revalidation fails after entering invalid string

### Expected outcome
It should revalidate when entering a valid string or picking a date.

### Actual outcome
It remains invalid in styling and invalid property.

### Live Demo
https://vaadin.com/elements/vaadin-date-picker/html-examples/date-picker-basic-demos

### Steps to reproduce
1. Put a `vaadin-date-picker` element in the page.
2. Open the page in a web browser.
3. Click the input of `vaadin-date-picker` element.
4. Enter an invalid string in the input (e.g. "qwert")
5. Click somewhere else to blur input
6. Click input again
7. Select a date or enter a valid date
8. Click somewhere else to blur again
-> date-picker remains invalid.

Actually I found no way to make it valid again except for: I use it to define a date range and the min of one is the value of the other. When the other's value is changed it re-validates successfully.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Fixed by #492
