### ISSUE TITLE
Version mismatch for vaadin-control-state-mixin

### ISSUE THREAD

**Issue by marcelojgarcia** [vaadin/vaadin-date-picker#489]
### Description
I'm getting "ECONFLICT" error messsage when installing vaadin-date-picker with "bower install --save vaadin/vaadin-date-picker"

### Expected outcome
Have the component installed correctly.

### Actual outcome
$ bower install --save vaadin/vaadin-date-picker
bower vaadin-date-picker#*      cached https://github.com/vaadin/vaadin-date-picker.git#2.0.7
bower vaadin-date-picker#*    validate 2.0.7 against https://github.com/vaadin/vaadin-date-picker.git#*
bower vaadin-control-state-mixin#^2.0.0           cached https://github.com/vaadin/vaadin-control-state-mixin.git#2.0.0
bower vaadin-control-state-mixin#^2.0.0         validate 2.0.0 against https://github.com/vaadin/vaadin-control-state-mixin.git#^2.0.0
bower vaadin-text-field#^1.0.0                    cached https://github.com/vaadin/vaadin-text-field.git#1.1.0
bower vaadin-text-field#^1.0.0                  validate 1.1.0 against https://github.com/vaadin/vaadin-text-field.git#^1.0.0
bower vaadin-control-state-mixin#^1.0.1           cached https://github.com/vaadin/vaadin-control-state-mixin.git#1.1.8
bower vaadin-control-state-mixin#^1.0.1         validate 1.1.8 against https://github.com/vaadin/vaadin-control-state-mixin.git#^1.0.1
bower                                          ECONFLICT Unable to find suitable version for vaadin-control-state-mixin

**Comment by web-padawan** [comment]
There was a version conflict due to broken release pulling in the wrong dependency version. It is now fixed and the fresh install no longer produces the conflict, therefore I am closing this issue.
