### ISSUE TITLE
Overlay content gets misaligned on narrow viewport

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#491]
1. Open date picker on a mobile device with narrow viewport
2. Swipe the year scroller visible
3. Close the data picker
4. Re-open the date picker
-> The layout looks as follows
![screenshot 2017-12-15 16 14 39](https://user-images.githubusercontent.com/1222264/34045837-666a0e8e-e1b3-11e7-9b14-59624272f856.png)

**Comment by jouni** [comment]
It probably because of the crazy tricks I did in the theme to override some of the behavior 😳
