### ISSUE TITLE
Integration with `iron-form`

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-date-picker#51]
`iron-form` support initial plan:
- Add `Polymer.IronFormElementBehavior` and `Polymer.IronValidatableBehavior`
- Separate properties for `selectedDate` (Date object, default `null`) and `value` (formatted String, empty by default)
  - both writeable, updating each other if needed
  - `value` might also support Date assignment
- `valueFormat` property. Use input field `format` when empty.
- Date formatting depends on locale. Update `value` on locale change.

**Comment by tomivirkki** [comment]
I don't see why this should depend on localization. After all, the value received by iron-form is often also the "raw" data sent to the server for further processing so it shouldn't depend on the locale a client happens to be using. date.getTime() or date.toString() could be used to provide a consistent value?

**Comment by tomivirkki** [comment]
Discussed this and agreed with the following approach: We'll change the type of datepicker.value from Date to String and it should format the way that &lt;input type="date"&gt; formats its value ("YYYY-MM-DD").

This complies better with existing standards, iron-form and the fact that the components should select dates, not time (Date type has too detailed resolution).
