### ISSUE TITLE
Native keyboard displays on mobile

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/vaadin-date-picker#520]
### Description
The `vaadin-date-picker` element causes the native on-screen keyboard to display on mobile.

### Expected outcome
Only the overlay should appear when input is clicked.

### Actual outcome
Overlay displays in mobile mode and the native keyboard is also displayed. When the keyboard is dismissed the overlay switches to desktop mode.

### Demo
Before interaction
<img src="https://user-images.githubusercontent.com/900868/37391013-a272ef2c-2772-11e8-9fca-23256d4d934a.jpg" alt="Before interaction" width="400"/>

After click
<img src="https://user-images.githubusercontent.com/900868/37391025-a9660b7a-2772-11e8-9f28-bae18e713617.jpg" alt="After click" width="400"/>

On keyboard dismiss
<img src="https://user-images.githubusercontent.com/900868/37391033-ae739eca-2772-11e8-89fe-a35ce2a003bd.jpg" alt="After click" width="400"/>

### Steps to reproduce
1. Put a `vaadin-date-picker` element in the page.
2. Open the page in a web browser on Android.
3. Click the input of `vaadin-date-picker` element.

### Browsers Affected
Confirmed on
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] Android Chrome
- [x] Android Firefox

### Vaadin Platform version
10.0.0.beta1

**Comment by tomivirkki** [comment]
The [latest release demos](https://cdn.vaadin.com/vaadin-date-picker/3.0.0-beta4/demo/) work fine on my Android device

**Comment by oluwasayo** [comment]
[Latest release demos](https://cdn.vaadin.com/vaadin-date-picker/3.0.0-beta4/demo/) confirmed working on my Android. I guess platform beta1 contains an older version. I'm using date picker from a Flow application.

**Comment by oluwasayo** [comment]
Platform seems to contain `3.0.0-beta4` of the element (which is the latest release). I suspect `vaadin-date-picker-flow` might be responsible.

**Comment by web-padawan** [comment]
Verifier once again with the demos at vaadin.com, stable version included in V10 works fine. Closing.
