### ISSUE TITLE
Overlay buttons don’t adapt to `--lumo-border-radius`

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-date-picker#523]
When using a large Lumo border-radius, the button padding is not affected like it affects normal `<vaadin-button>` elements.

Here’s how the calc works for normal buttons: https://github.com/vaadin/vaadin-button/blob/master/theme/lumo/vaadin-button.html#L29

We should add a suitable calc here as well: https://github.com/vaadin/vaadin-date-picker/blob/master/theme/lumo/vaadin-date-picker-overlay-content.html#L126

**Comment by web-padawan** [comment]
@jouni is there a way fix this now with the updated border radius scale landed in 1.4 ?

**Comment by jouni** [comment]
> @jouni is there a way fix this now with the updated border radius scale landed in 1.4 ?

No, that doesn’t affect this issue.

The [tertiary buttons don’t adapt to the border radius either](https://github.com/vaadin/vaadin-button/blob/master/theme/lumo/vaadin-button-styles.html#L128-L130). And I’m not really sure anymore if they should.

I’ll just close this as wontfix or invalid.
