### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by tomalec** [vaadin/vaadin-date-picker#527]
### Description
The `vaadin-date-picker` element does not work in Firefox.

### Expected outcome
It should look and behave somewhat similar to Chrome

### Actual outcome
It shows an empty grayish rectangle

### Live Demo
https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-basic-demos

### Steps to reproduce

1. Put a `vaadin-date-picker` element in the page.
2. Open the page in a web browser.

### Browsers Affected

- [ ] Chrome
- [x] Firefox (59.0.2)
- [?] Safari
- [ ] Edge
- [ ] IE 11
- [?] iOS Safari
- [?] Android Chrome

![obraz](https://user-images.githubusercontent.com/17435/38137706-8643363e-3426-11e8-838d-460104412d16.png)

I also tried empty page with just polyfill loaded:
![obraz](https://user-images.githubusercontent.com/17435/38137721-97593964-3426-11e8-8315-62b7d92f82a6.png)

**Comment by web-padawan** [comment]
I am unable to reproduce the issue with the same version. Do you have any browser extensions like LastPass? Some of them might affect polyfills.

**Comment by moderndeveloperllc** [comment]
@tomalec Can you provide the OS you are using and the Firefox Web Developer Console output for that page? I tried FF59 on macOS, Win 8.1, and Win 10 and didn't see an issue either. @web-padawan FWIW, I have 1Password and haven't had any issues with Vaadin elements. Actually, FF is the only browser that will find `vaadin-password-field` fields for filling.

**Comment by tomalec** [comment]
@web-padawan @moderndeveloperllc Thanks for instand feedback. I didn't have LastPass nor any other password-related extensions, all I had was: Github refined, Grammarly and AdBlock.

I've reinstalled FF as I encountered problems on other sites. Now the problem is gone, and I'm not able to reproduce it neither.
