### ISSUE TITLE
Could not find style data in module named vaadin-date-picker-overlay-default-theme

### ISSUE THREAD

**Issue by pdesjardins90** [vaadin/vaadin-date-picker#537]
### Description
I get this warning using:
- vaadin-material-theme (0.3.0)
- vaadin-date-picker (v3.0.0-beta5)

`Could not find style data in module named vaadin-date-picker-overlay-default-theme`

**Comment by pdesjardins90** [comment]
Culprit is in vaadin-material-theme/vaadin-date-picker.html, line 134-136: 
```html
<dom-module id="material-date-picker-overlay" theme-for="vaadin-date-picker-overlay">
  <template>
    <style include="vaadin-date-picker-overlay-default-theme">
...
```

**Comment by web-padawan** [comment]
Thanks for the issue. The Material theme has not yet been updated to match the latest component versions, and is likely to be postponed until we get Polymer 3 stable versions. Sorry about the mess there, some work has been started in vaadin/vaadin-material-theme#32 but that does not yet include date-picker.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-material-theme#35
