### ISSUE TITLE
Providing parse Date function makes the input highlighted as invalid : i18n Object

### ISSUE THREAD

**Issue by osamamaruf** [vaadin/vaadin-date-picker#549]
### Description
Invalid highlight appears when the i18n object is given a parseDate method. I am using vaadin-date-picker v3.0.0.

### Expected outcome
The formatted date should appear without the invalid highlight.

### Actual outcome
The formatted date appears with an invalid highlight indicating the the provided format is incorrect.

### Live Demo
http://output.jsbin.com/texalef
Code:
http://jsbin.com/texalef/edit?html

### Steps to reproduce
1. Set the parseDate property by passing a function.

Note: moment is being used as a third party library.

### Browsers Affected
Checked on 
- [x] Chrome
- [x] IE 11

**Comment by tomivirkki** [comment]
Hi @osamamaruf,
The component expects `parseDate` to return an object in format `{day, month, year}` instead of a Date object.
https://github.com/vaadin/vaadin-date-picker/blob/master/src/vaadin-date-picker-mixin.html#L170

**Comment by osamamaruf** [comment]
Hi @tomivirkki ,
Thank you for the prompt response. That is indeed the case. By returning `{date,month,year}` all is well now.
However,
I googled again and this is shown in the link below:
 https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-advanced-demos

but I was unfortunate to find the below example first where I was misled into returning the date object from `parseDate`:
https://vaadin.com/docs/elements/vaadin-date-picker/vaadin-date-picker-localization.html.

**Comment by tomivirkki** [comment]
Ooh, that page shouldn't exist anymore (we'll get this fixed). The API for previous version of the element indeed used a Date object but that was changed for the most recent major. Thanks for pointing that our and sorry for the inconvenience.
