### ISSUE TITLE
Themability

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-date-picker#55]
The component should use colors from the `paper-styles`.

A couple of notices also related to the calendar and clear icons.

* Anton: Currently the target size are 24px × 24px. Material design guideline suggest at least 48px × 48px. But that would feel too big to align with an input field.
* Anton: Would be nice to have a ripple effect for icons.

**Comment by platosha** [comment]
While implementing, please make sure that we're not using fractional font-sizes in the element. We should rather use pixel-accurate font-sizes, either by using mixins from "paper-styles/typography.html", or with "px" values.
