### ISSUE TITLE
DatePicker Locale Not Working in Mobile

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-date-picker#594]
### Description
DatePicker setLocale method working fine in Laptop browsers but not working in mobile phone browsers including Chrome.

### Expected outcome
When I choose the date from DatePicker from my mobile phone, it should work according to my locale.

Example (Locale TR -> Working fine in laptop browsers but not in mobile browsers):

dpStartDate = new DatePicker( "" );
dpStartDate.setPlaceholder( "Başlangıç Tarihi" );
dpStartDate.setLocale( new Locale( "tr", "TR" ) );

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Thanks for the issue. This repo is for the Web Component, and for its Java counterpart we have different repo. I will move it there so that our teammates could handle it appropriately.

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-date-picker-flow#116

**Comment by ugurdoksan** [comment]
When this bug will be fixed?
