### ISSUE TITLE
Support ISO 8601 Extended Format

### ISSUE THREAD

**Issue by MacTheZazou** [vaadin/vaadin-date-picker#600]
It would be very nice to support the ISO 8601 Extended Format or directly JS date object.

It's not very convenient to have to convert all the time our Date object & not having the possibility to directly use the Date.prototype.toISOString function.

**Comment by web-padawan** [comment]
Thanks for the issue. We have been previously using `toISOString` internally, see #596 as an example of the issue which used to exist because of that. See also discussion in #449

**Comment by web-padawan** [comment]
Closing per above comment.
