### ISSUE TITLE
how to custom "style"  vaadin-date-picker

### ISSUE THREAD

**Issue by omarmok** [vaadin/vaadin-date-picker#604]
how to custom "style"  vaadin-date-picker,

like posiition for vaadin-date-picker-overlay

    left: 849.344px;
    top: 186px;

 i want to change this,

[part="input-field"] change color for input

:host {
    align-items: flex-start;
    justify-content: flex-start;
}

**Comment by tomivirkki** [comment]
Hi, with the newest versions of Vaadin components, the assigned `theme` attribute will propagate to the child components. To change the text-field label color, you can now
1. Assign `theme="my-theme"` attribute to the date picker
2. Create a theme-for module for text field that targets only a host that has the previous "theme" attribute.

Here's a live example:
https://glitch.com/edit/#!/certain-denim

**Comment by punkratz312** [comment]
@tomivirkki thanks.

**Comment by punkratz312** [comment]
@tomivirkki could you please tell, how to change the focused style as well. Extending the great example by :focus selector does not work: 
![image](https://user-images.githubusercontent.com/8830888/47986496-39633f80-e0dd-11e8-8ad1-df3e74d5ac27.png)

Thanks.

**Comment by tomivirkki** [comment]
Use the "focused" host attribute instead:
`:host([theme="my-theme"][focused]) [part~="label"] {`

**Comment by tomivirkki** [comment]
Here's the list of available state attributes for `<vaadin-text-field>`: https://github.com/vaadin/vaadin-text-field/blob/master/src/vaadin-text-field.html#L107

**Comment by punkratz312** [comment]
@tomivirkki awesome, thanks.

One last thing needed for me to make it work in my case. How can i add the theme-for attribute in a polymer 3.0? I hope thats it to make it work.
![image](https://user-images.githubusercontent.com/8830888/47986902-52202500-e0de-11e8-84a2-c21f03e4dd59.png)

Thanks.

**Comment by tomivirkki** [comment]
It needs to be wrapped inside a `<dom-module><template>` in P3 also (the API hasn't changed). Unfortunately that's not as convenient with es modules as it was with html imports. We're currently prototyping an improved theming API. Here's how the dom-modules are generated by Lumo: https://unpkg.com/@vaadin/vaadin-text-field@2.1.3/theme/lumo/vaadin-text-field-styles.js
