### ISSUE TITLE
Rendered as invalid when required=true even without any interaction done.

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-date-picker#605]
### Description
 When it’s marked as required it shows as invalid even without any interaction done.

### Expected outcome
`vaadin-date-picker` is in the default state without any user actions

### Actual outcome
`vaadin-date-picker` is marked as invalid without any user actions

### Live Demo
- https://glitch.com/edit/#!/helpful-yoke?path=index.html:10:30
- https://helpful-yoke.glitch.me/

**Comment by web-padawan** [comment]
Appears to be a regression introduced in 0e0230e

**Comment by limonte** [comment]
Released in https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.3.0-alpha2 🎉
