### ISSUE TITLE
How can I get started as a complete beginner?

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-date-picker#612]
I'm new to web dev. Is there a bare minimum html example I can see to use a component? I don't want to use angular or other frameworks. I've done `npm i @vaadin/vaadin-date-picker --save`

My `index.html` so far:

```html
<html>
<head>
    <title>Date picker</title>

    <!-- load webcomponents bundle, which includes all the necessary polyfills -->
    <script src="node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js"></script>
    <script src="script.js" type="module"></script>
</head>

<body>
    <vaadin-date-picker></vaadin-date-picker>
</body>
```

`script.js`:
```
import './node_modules/@vaadin/vaadin-date-picker/vaadin-date-picker.js'
```

But I get this error in chrome: `Uncaught TypeError: Failed to resolve module specifier "@vaadin/vaadin-lumo-styles/sizing.js". Relative references must start with either "/", "./", or "../".`

**Comment by web-padawan** [comment]
Hi, this error is related to the fact that `vaadin-date-picker` is using imports with "bare module specifiers", not the paths, and browser can't handle it automatically.

You might be interested in using some tools to handle that, especially:
- Polymer CLI: https://www.polymer-project.org/3.0/docs/tools/polymer-cli
- Webpack and its dev server: https://github.com/web-padawan/polymer3-webpack-starter

If you have some React background, you might be interested in using our React example:
https://github.com/vaadin/base-starter-react/tree/p3-preview

**Comment by Kurren123** [comment]
It looks like this with `es5-bundled`: 

![image](https://user-images.githubusercontent.com/3525980/47218234-fa29b480-d3a2-11e8-8d17-2bf0eae6117a.png)

My aim is just to have an `index.html` page, reference one `script.js` and be able to use a vaadin component in the page.

**Comment by web-padawan** [comment]
@Kurren123 note that you should still have at least some build configuration. As a development server, you can use `polyserve` with the `--npm` flag as demonstrated here:
https://glitch.com/edit/#!/thin-tapir?path=index.html:1:0

For proper building using Polymer CLI, you would need a proper `polymer.json` which you can find here: https://github.com/Polymer/pwa-starter-kit/blob/master/polymer.json

We also have our own template for Polymer CLI which will be updated to Polymer 3 quite soon.

**Comment by Kurren123** [comment]
@web-padawan thanks for replying. My `polymer.json` is simply:

```JSON
{
  "entrypoint": "src/index.html",
  "shell": "src/import-components.js",
  "sources": [
    "package.json"
  ],
  "extraDependencies": [
    "node_modules/@webcomponents/webcomponentsjs/**"
  ],
  "builds": [
    {
      "preset": "es6-unbundled"
    }
  ],
  "moduleResolution": "node",
  "npm": true
}
```
When building it also says `[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.` which I suspect is causing the unstyled calendar issue?

**Comment by Kurren123** [comment]
@web-padawan This is my repository: https://github.com/Kurren123/vaadin-date-picker-example

Thanks again for replying so quickly

**Comment by web-padawan** [comment]
> When building it also says [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB. which I suspect is causing the unstyled calendar issue?

You can simply ignore this warning. It is not expected to cause any issues, and this is related to Polymer tools, not the components themselves.

Also, it is better to place `index.html` at the root project level, not inside of the `src` folder, as you are importing from `node_modules` which is one level above and Polymer tools might have problems with it.

**Comment by Kurren123** [comment]
Thanks for your help, it works perfectly when using `polymer serve` and moving the index.html into the root directory.
