### ISSUE TITLE
How can I keep the light datepicker always visible?

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-date-picker#615]
If I wanted the light date picker as an always visible component on the page (rather than a popup), is there an easy way to do this?

Thanks for your patience, still new to web dev.

**Comment by web-padawan** [comment]
Hi, thanks for the question and sorry for not answering earlier. This could be done by using `vaadin-month-calendar` or `vaadin-date-picker-overlay-content` component, however please note it is not considered as part of a public API and therefore might be changed in the next releases.

You can look at the unit tests to see what properties should be set to make these components work separately (especially, `i18n` object is required, and some others too):
https://github.com/vaadin/vaadin-date-picker/blob/master/test/overlay.html
https://github.com/vaadin/vaadin-date-picker/blob/master/test/month-calendar.html

Also, you will likely have to copy and paste some styles manually, especially to set max-width and max-height, which is currently done in the overlay styles.

**Comment by Kurren123** [comment]
Thanks for your help!
