### ISSUE TITLE
WebComponentsReady EventListener not being added/called. 

### ISSUE THREAD

**Issue by dwkns** [vaadin/vaadin-date-picker#620]
### Description

Date Picker works as expected but 'WebComponentsReady' Event Listener is not being called.

**HTML**
```html
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title>Date Picker Test</title>
</head>
<body>
    <vaadin-date-picker id="weeks" show-week-numbers></vaadin-date-picker>
    <script src="js/bundle.js"></script>
</body>
</html>

```

**JS** 
```javascript
import '@vaadin/vaadin-date-picker/vaadin-date-picker.js';

window.addEventListener('WebComponentsReady', function() {
     console.log('WebComponentsReady Called');
    // Async call needed here for IE11 compatibility.
    Polymer.Base.async(function() {
        var datepicker = document.querySelector('vaadin-date-picker#weeks');
        datepicker.set('i18n.firstDayOfWeek', 1);
    });
});
```
bundle.js is being created by [Rollup](https://rollupjs.org/guide/en).

**rollup.config.js**
```javascript
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
    input: 'source/js/main.js',
    output: {
        file: 'build/js/bundle.js',
        format: 'iife'
    },
    plugins: [
        resolve({
            preferBuiltins: true
        }),
        commonjs(),
        babel({
            exclude: 'node_modules/**'
        })
    ]
};
```

### Expected outcome
Weeks should be shown on component.
'WebComponentsReady Called' should be printed to Console.

Neither happen.

### Steps to reproduce
See code above

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
Hi, thanks for the issue. The `WebComponentsReady` event is produced by webcomponents.js polyfill which you are apparently not using. Yo can read about it here: https://github.com/webcomponents/webcomponentsjs#webcomponentsready-event

Our demos are wrapped in this example especially because of the fact that they should also work in polyfilled browsers like Edge and IE11, where waiting for this event is required.

**Comment by web-padawan** [comment]
Closing in favour of vaadin/vaadin-demo-helpers#64

**Comment by dwkns** [comment]
Makes sense. But maybe update the website / examples to make this clear?

**Comment by web-padawan** [comment]
Yes, see above the reference to the issue where the update should be tracked.

**Comment by web-padawan** [comment]
@dwkns FYI, the 3.3.2 version has been released including the fix:
https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.3.2

**Comment by dwkns** [comment]
@web-padawan Releases page links to different examples than the ReadMe page. 
[Release page](https://github.com/vaadin/vaadin-date-picker/releases/tag/v3.3.2) points to [this page](https://cdn.vaadin.com/vaadin-date-picker/3.3.2/demo/#date-picker-basic-demos) (correct info).
[ReadMe](https://github.com/vaadin/vaadin-date-picker/blob/master/README.md) points to[ live website](https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-basic-demos) (incorrect info)
