### ISSUE TITLE
setLocale lossing after Tab switch

### ISSUE THREAD

**Issue by Fr33z3m4n** [vaadin/vaadin-date-picker#627]
### Description
If you use the Date Picker in a tab and the tabs change, the DatePicker Textfield loses the setLocale setting.

Example:
```
setLocale (Locale.GERMAN);
setLocalGerman ();
```
```
private void setLocalGerman () {
setI18n (new DatePickerI18n (). setWeek ("week") ...........
}
```
After switching back to the tab, the English time setting is displayed again.

Workaround:
```
@Override
protected void onAttach (AttachEvent attachEvent) {
setLocale (Locale.GERMAN);
setLocalGerman ();
super.onAttach (attachEvent);
}
```
![date-picker-ticket-1](https://user-images.githubusercontent.com/1181557/51665530-43019280-1fbc-11e9-8ed8-486c2dcbb08c.PNG)
![date-picker-ticket-2](https://user-images.githubusercontent.com/1181557/51665536-44cb5600-1fbc-11e9-8a35-561e32fdb4d3.PNG)

### Steps to reproduce
1. Put a `vaadin-date-picker` element in the first Tabpage.
2. Open the page in a web browser.
3. Click the input of `vaadin-date-picker` element.
4. Click 2nd Tab
5. Click 1st Tab
6. Format reverted to English

### Browsers Affected
- [x ] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by web-padawan** [comment]
This issue was moved to vaadin/vaadin-date-picker-flow#152
