### ISSUE TITLE
IE11 vaadin date picker exception in overlay

### ISSUE THREAD

**Issue by osamamaruf** [vaadin/vaadin-date-picker#633]
### Description
Vaadin date Picker throws exception in IE11

### Expected outcome
Vaadin date picker should render properly in IE11

### Actual outcome
An exception is thrown stating 
> cannot read property 'appendchild' of undefined

on line 

`this.$.content.shadowRoot.appendChild(this._instance.root);` in [vaadin-overlay.html](https://github.com/vaadin/vaadin-overlay/blob/master/src/vaadin-overlay.html)

### Steps to reproduce
1. Put a `vaadin-date-picker` element in the page.
2. Open the page in IE 11.
3. No element visible

### OS
**OS** Windows 10
**IE Version** 11.316.17763.0
**IE Update Version** KB4486474

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [X] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by samiheikki** [comment]
Are you compiling your code to es5?

I'm having the following setup (and it works on IE11):
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
  <title>vaadin-date-picker Examples</title>
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="../vaadin-date-picker.html">
</head>

<body>
  <vaadin-date-picker></vaadin-date-picker>
</body>
</html>
```

and running it with command `polymer serve --compile always`

**OS** Windows 10
**IE Version** 11.590.17134.0
**IE Update Version** KB4486474

![date-picker](https://user-images.githubusercontent.com/8615573/53299208-0980a900-3840-11e9-91dc-21d18beb8435.PNG)

**Comment by samiheikki** [comment]
Discussed with @tomivirkki and decided to close the ticket as date-picker seems to work as expected.
@osamamaruf add further info if you need the issue to be re-opened.
