### ISSUE TITLE
A value can't be selected by clicking on IE11

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#634]
1. Open the first demo on IE11
2. Select a value by clicking a date on the dropdown
-> Placeholder is shown, no value is visible

**Comment by yuriy-fix** [comment]
BTW, tests are broken on `master` in ie11 cause `this.$.overlay` is not available over here: https://github.com/vaadin/vaadin-date-picker/commit/2d86da5dd1a92fdd9c1d39b6562c36e528879897#diff-0f7cab7f0a6b1e79bf518eb211b482deR328

**Comment by web-padawan** [comment]
Let's consider using `disable-upgrade` instead of `dom-if` as in vaadin/vaadin-combo-box#776
