### ISSUE TITLE
Vaadin date picker light - material theme - is missing single disabled dates styling

### ISSUE THREAD

**Issue by AndreSilva1993** [vaadin/vaadin-date-picker#636]
### Description
In the following file `theme/material/vaadin-month-calendar-styles.html` there should be a rule to style individual disabled dates in a month like there is in the default lumo style (https://github.com/vaadin/vaadin-date-picker/blob/master/theme/lumo/vaadin-month-calendar-styles.html#L119).

Including the following rule in the file `theme/material/vaadin-month-calendar-styles.html` fixes the issue:

```
[part="date"][disabled] {
  color: var(--material-disabled-text-color);
}
```

### Expected outcome
The single disabled days in a month should be greyed out like in the lumo style.

### Actual outcome
The days are correctly disabled as the user can't select them but the color remains unaltered which does not happen in the default lumo style.

### Steps to reproduce
1. Put a `vaadin-date-picker-light` element in the page and apply the material theme.
2. Define a `min` date as **2019-02-15** for instance.
3. Open the datepicker.
4. The previous days in February should be greyed out which is not currently happening.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by realansgar** [comment]
This also happens when using the not light version, probably because the material styles get reused between both versions.

### Live Example
![vaadin-date-picker material disabled bug](https://user-images.githubusercontent.com/39188180/53981858-c7931500-4113-11e9-9427-9dc193917cc8.gif)

![image](https://user-images.githubusercontent.com/39188180/53981872-d11c7d00-4113-11e9-967e-49b312eccc2c.png)

**Comment by realansgar** [comment]
### Possible Fix
In  `.../vaadin-date-picker/theme/material/vaadin-month-calendar-styles.html` at line 31 add this snippet:
`[part="date"][disabled],`
![image](https://user-images.githubusercontent.com/39188180/53982649-b3501780-4115-11e9-966f-c1aeaafd49e8.png)
