### ISSUE TITLE
The date picker in "Localizing" demo is marked invalid

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#639]
When the value is changed, the date picker in "localizing" demo is marked as invalid for no reason.

**Comment by samiheikki** [comment]
Error is with Sugar.js. I created a ticket there: https://github.com/andrewplummer/Sugar/issues/648

The demos are using 2.0.6 version while the 2.0.4 version is working so we could use that in our bower.json. @tomivirkki WDYT?

**Comment by samiheikki** [comment]
Looking at Sugar.js recent development, I don't think a fix will done any time soon. So I think better to use Sugar 2.0.4 as it is just a development dependency. https://github.com/vaadin/vaadin-date-picker/pull/642
