### ISSUE TITLE
Datepicker - how can I set the default date format?

### ISSUE THREAD

**Issue by Kurren123** [vaadin/vaadin-date-picker#647]
In [the docs](https://www.webcomponents.org/element/vaadin/vaadin-date-picker/elements/vaadin-date-picker#property-i18n) it says I can use `datePicker.i18n.formatDate = ...` to change the date display. Is there a way I can set this once so that wherever I put `<vaadin-date-picker>` in the html it shows dates in that format without having to go through and set each `datePicker` in js?

Thanks for any help!

**Comment by web-padawan** [comment]
Thanks for the issue. The best way to achieve it would be extending `vaadin-date-picker`:

```js
class MyDatePicker extends customElements.get('vaadin-date-picker') {
  constructor() {
    super();
    this.i18n.formatDate = function() {
      /* override as you need */
    };
  }
}

customElements.define('my-date-picker', MyDatePicker);
```

We could consider having a static property as a feature for doing the same, if we get more requests. But in general, extending custom elements is what the users are supposed to do in cases like this.

**Comment by Kurren123** [comment]
Excellent, thank you very much for your quick response.

**Comment by Kurren123** [comment]
@web-padawan another basic question, I'm getting the error 
```
Class constructor DatePickerElement cannot be invoked without 'new'
```

Am I meant to have `import '@vaadin/vaadin-date-picker'` at the top or do I import something else?

My code so far:

```javascript
import '@vaadin/vaadin-date-picker'

class MyDatePicker extends customElements.get('vaadin-date-picker') {
  constructor() {
    super();
  }
}

customElements.define('my-date-picker', MyDatePicker);
```

Thanks again for your help

**Comment by web-padawan** [comment]
In case you are using npm, you can update to the following example:

```
import { DatePickerElement } from '@vaadin/vaadin-date-picker/src/vaadin-date-picker.js';

/* you can use "material" here instead of "lumo" if you need */
import '@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker.js';

class MyDatePicker extends DatePickerElement {
  constructor() {
    super();
  }
}

customElements.define('my-date-picker', MyDatePicker);
```

Regarding the error, it looks like you are not correctly transpiling node_modules.
Are you using webpack and `babel-loader` in your project?

**Comment by tomivirkki** [comment]
Could be you're missing an import for `custom-elements-es5-adapter` https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs

**Comment by Kurren123** [comment]
Thanks @web-padawan and @tomivirkki. I tried your code sample and went through [this tutorial](https://vaadin.com/tutorials/using-web-components) and everything worked 😄
