### ISSUE TITLE
Setting theme cuases JS exception

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-date-picker#651]
@jmycka commented on [Thu Apr 04 2019](https://github.com/vaadin/vaadin-date-picker-flow/issues/171)

Setting theme for DatePicker element causes JS exception:
`TypeError: this._setTheme is not a function`

Problem occurs with web component v3.3.3 (platform release 13.0.3)

See code below to reproduce error:
`final DatePicker dp = new DatePicker();
dp.getElement().getThemeList().add("small");`

---

@ZheSun88 commented on [Fri Apr 05 2019](https://github.com/vaadin/vaadin-date-picker-flow/issues/171#issuecomment-480154657)

Hi, 
This is the repo for `date-picker` flow integration. I will move this issue to the webcomponent repo so that you can get proper help.

**Comment by web-padawan** [comment]
Confirmed at https://cdn.vaadin.com/vaadin-date-picker/3.3.3/demo/
Appears to be a regression due to introducing `disable-upgrade-mixin`
