### ISSUE TITLE
Let DateField support an alternative date format

### ISSUE THREAD

**Issue by cdir** [vaadin/vaadin-date-picker#662]
### Description

In #661 is already described that we need some way to enter a date more quickly by using only two digit years. In business applications with many date input fields the user is used to enter the date without the date seperators. That seperators are created automatically or after leaving the field.

### Expected outcome
For example a date could be entered using just 6 digit. 010121 will be transformed to 01/01/2021. It may be even possible to enter the format dependent seperator automatically (dependent on the locale). In date format with day or month first, the seperator could be added automatically after entering two digits if there is not yet a seperator. An additional seperator will be automatically ignored.

A simpler approach may be to have the ability to give a primary and a list of alternative date formats. If the primary date format does not leads to a valid date, the alternative date formats are tried out until there is a valid date. The developer have to make sure that the order of the date format is useful. Afterwards the date is formatted in primary date format. For a german date picker I would use dd.MM.YYYY as primary format and ddMMYYYY as an alternative format. With #661 also two digit year should be supported this way.

**Comment by web-padawan** [comment]
Use [`i18n` property](https://cdn.vaadin.com/vaadin-date-picker/4.0.1/#/elements/vaadin-date-picker#property-i18n) and especially `parseDate` and `formatDate` if you need a custom date format.
That way you could use any separator you want, as well as update it based on locale etc.

See also the [example](https://cdn.vaadin.com/vaadin-date-picker/4.0.1/demo/#date-picker-localization-demos) of using `i18n` property for localisation.

**Comment by web-padawan** [comment]
Closing per above comment.
