### ISSUE TITLE
Add support for date patterns

### ISSUE THREAD

**Issue by mhosio** [vaadin/vaadin-date-picker#663]
As a user I would like to use patterns such as "d.M.yyyy" for formatting the date. This functionality has been used by many on the earlier versions of the Vaadin Framework and it is still not yet available for the new date picker.

**Comment by web-padawan** [comment]
Please check my comment here https://github.com/vaadin/vaadin-date-picker/issues/662#issuecomment-496513325

We already provide the `i18n` API which is enough to implement the custom parser and formatter.

Baking support for various patterns into `vaadin-date-picker` itself would make it more opinionated and less generic, and also it would result in growing bundle size (which is already quite big).

**Comment by mhosio** [comment]
Now that I think of it, I agree with you. And the api makes it fairly easy to integrate third party date parsing libraries when pattern support is needed. This is more of an issue for the java-api (flow) where overriding i18n functions is trickier. However, there seems to be already an issue regarding that so I will close this one now. Thanks for the input.
