### ISSUE TITLE
Focused date not set when opening overlay via up/down key

### ISSUE THREAD

**Issue by mas4ivv** [vaadin/vaadin-date-picker#669]
When I open the overlay via up or down key on an empty date picker, the current date is focused in the calendar, but not selected. Hitting enter will close the overlay, leaving the input field empty. 

Using any arrow key will select a date and transfer it into the input field. So if I want to select the current date via keyboard I have to move the cursor back and forth once and then hit enter to close the overlay. Instead it should be sufficient to hit enter directly after opening the overlay.

**Comment by jouni** [comment]
The current behavior is a bit problematic indeed. The pulsating focus highlight “hint” (call it pre-focus) is unclear. It highlights the date which will be focused if you move the focus to the calendar using the tab key. But it does also look like you could select that date by pressing enter/space as it looks like it’s focused.

Alternatives:

1. When focus is on the input field, move focus to the pre-focused date (i.e. current date by default) when pressing up/down arrow keys
     - Won’t break existing behavior that much, it’s more of a fix to avoid having to press down+down+up+enter to select the current date (down+down+enter would suffice).
     - The least amount of changes

2. Don’t pre-focus the current date on the first arrow key press or when focusing the field with a click. Focus the current day only after the user moves the focus to the calendar either with the tab or up/down arrow keys.
      - The only difference to the first option is to not have a pre-focus highlight, which might make the behavior clearer

3. Show pre-focus and pre-select the current date on the first arrow key press (i.e. fill the input field with the date). Pressing enter or blurring the field would update the field value. Click-to-focus would still just open the calendar but not show pre-focus or pre-select the current date.
      - Could break existing user flows if users are not expecting the current date to become selected after pressing up/down arrow key and blurring the field.

I would like us to quickly prototype these options and see which one feels best. Option 3 is least favorable as it can be considered as a breaking change, which options 1 and 2 can be considered as fixes instead.

**Comment by yuriy-fix** [comment]
The functionality that is needed in order to satisfy the requirements and make them work by default seems to require a breaking behavioural change. I have created another "prototype" ticket in order to find a proper way to do that based on @jouni comment.

In the meanwhile, I have created an example with desired behaviour on Glitch: https://glitch.com/edit/#!/date-picker-arrows?path=index.html:12:46 .
The code that helps to achieve it:
```
datepicker.$.overlay.addEventListener('vaadin-overlay-open', e =>
        datepicker._overlayContent._moveFocusByDays(0));
```
Does it help with the issue, @mas4ivv ?

**Comment by mas4ivv** [comment]
Yes, this is exactly the wanted behaviour. I can add this code in our app, so that all three options mentioned by @jouni would be OK for us as long as this work-around still works.

**Comment by yuriy-fix** [comment]
Most probably the updated behaviour will land to the next minor/major of the component after the prototyping step.

I am closing this one if favour of https://github.com/vaadin/vaadin-date-picker/issues/690.
