### ISSUE TITLE
Modal paper-dialog cuts of date picker

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#67]
vaadin-date-picker gets cut off by modal paper-dialog. Needs overflow: visible; on the paper-dialog to work properly. Workaround should be documented unless we can think of a good solution.

<img width="503" alt="screen shot 2016-02-24 at 3 14 03 pm" src="https://cloud.githubusercontent.com/assets/883698/13304430/6bd95b98-db09-11e5-8aa4-da994f28767a.png">

**Comment by tomivirkki** [comment]
The clipping in this case is caused by an `overflow-y: scroll` rule in the app CSS https://github.com/vaadin/expense-manager-demo/blob/master/client/app/elements/expense-editor.html#L27.

By default paper-dialog has `overflow: visible` which causes no issues with iron-dropdown.
