### ISSUE TITLE
The overlay is empty on iOS 12 Safari with Material theme

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#676]
For some reason the overlay doesn't get populated on iOS 12 Safari with Material theme in use. This can be worked around by forcing a dummy opening animation for the overlay with:

```html
<dom-module id="material-date-picker-overlay-animation" theme-for="vaadin-date-picker-overlay">
  <template>
    <style>
      @keyframes material-overlay-animation {
        100% {
          opacity: 1;
        }
      }

      :host([opening]),
      :host([closing]) {
        animation: 0.1s material-overlay-animation;
      }
    </style>
  </template>
</dom-module>
```

...so the opening sequence follows vaadin-overlay's `_enqueueAnimation` -> `finishOpening` [logic](https://github.com/vaadin/vaadin-overlay/blob/master/src/vaadin-overlay.html#L612).

With synchronous `finishOpening` (without animation = the default in Material theme) the overlay stays empty.

**Comment by yuriy-fix** [comment]
Cannot reproduce. Probably some change has fixed it already.
![Date-picker-ios](https://user-images.githubusercontent.com/29372419/69857309-665e3380-1298-11ea-9eb0-a3bc51b00a4e.gif)
