### ISSUE TITLE
User experience on Chrome on Android is confusing

### ISSUE THREAD

**Issue by nachokb** [vaadin/vaadin-date-picker#677]
### Description

On Android using Chrome 76 (and other browsers based on webview), when triggering the datepicker, the text field gets focus as well, so the keyboard is shown.

This is confusing because (1) these two elements completely block the field out, (2) typing anything, while potentially useful, is useless without seeing the field, and (3) the keyboard leaves little space for the picker;

This seems to be a regression on #484 / #488.

### Expected outcome

Picker opens up full screen (or almost); if the user wants to type, there could be a facility to switch to the keyboard (not important for me);

### Actual outcome

Both the phone's keyboard and the picker popup show up and obscure everything else.

### Live Demo

https://youtu.be/if59WSoMdLg

### Steps to reproduce

1. open demo page in android phone;
2. trigger any picker;

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] Android Chrome

**Comment by Haprog** [comment]
I can't reproduce this issue at https://cdn.vaadin.com/vaadin-date-picker/4.0.3/demo/ on my Samsung Galaxy S8, Android 9, Chrome 77.

Could it be some weird configuration/setting on your phone?

Could you try clearing your Chrome cache on Android or maybe rebooting your phone?

Can you check for updates to Chrome on Play Store and if you get an update, please test again?

Can you reproduce it on another Android phone?

**Comment by Haprog** [comment]
I even tried connecting a mouse to my phone but even then this issue doesn't happen.

**Comment by nachokb** [comment]
really? Sadly, Chrome was updated yesterday morning, so I can't test with an older version, and the next version is probably days off at least

**Comment by nachokb** [comment]
really? Sadly, Chrome was updated yesterday morning, so I can't test with an older version, and the next version is probably days off at least

That video is on Chrome 77.0.3865.73, Android 7.0 on an LG G5.

Same thing after clearing all browsing data for all time, same behavior on Chrome Beta channel.

Would you mind recording a screencast? Maybe I'm doing something differently.

There's also some weird behavior that I'm having trouble recording: (1) tap on the field, (2) dismiss the keyboard, (3) tap the field again; result: picker is triggered, but field is not in focus (so, no keyboard!). I would have expected the field to be focused, and trigger the keyboard.

**Comment by nachokb** [comment]
Ok, I've got no idea what's going on. Hope it's an older webview version or something
