### ISSUE TITLE
Binding value to a YYYY-MM-DD value fails

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#68]
Setting a YYYY-MM-DD value manually works, but if using Polymer data binding or programmatically setting the same string value, it does not get converted to a Date which causes and exception in date comparison (_dateEquals in vaadin-month-calendar.html)

**Comment by tehapo** [comment]
The current value is of type `Date`. You can bind a string value after this is implemented: https://github.com/vaadin/vaadin-date-picker/issues/51#issuecomment-187733692

**Comment by Bodhiz** [comment]
Hi, 

Before all thanks for this great date-picker.
Then I'm still gettin trouble with this. In my UT I try to set the value like this :
`myDatePicker.value = '2015-01-01';`
but I get the following error : 
```
Error: date1.getFullYear is not a function
  vaadin-month-calendar.Polymer._dateEquals at /vaadin-date-picker/vaadin-month-calendar.html:133
  vaadin-month-calendar.Polymer._isSelected at /vaadin-date-picker/vaadin-month-calendar.html:154
  TemplateInstance.Polymer.Base.extend._annotatedComputationEffect at /polymer/polymer.html:1591
  TemplateInstance.Polymer.Bind._modelApi._effectEffects at /polymer/polymer.html:1394
  TemplateInstance.Polymer.Bind._modelApi._propertySetter at /polymer/polymer.html:1378
  TemplateInstance.Polymer.Bind._modelApi.__setProperty [as __setPropertyOrig] at /polymer/polymer.html:1387
  TemplateInstance.Polymer.Templatizer.__setPropertyImpl [as __setProperty] at /polymer/polymer.html:3696
     dom-repeat.Polymer._forwardParentProp at /polymer/polymer.html:4470
                    dom-repeat.<anonymous> at /polymer/polymer.html:3776
  dom-repeat.Polymer.Base.extend._functionEffect at /polymer/polymer.html:1550
```

**Comment by tomivirkki** [comment]
Hi

Are you sure you’re using alpha4? If you set the value like you describe above, you’d get that exact error message with alpha2 (wrong value type), but with alpha4 this should work just fine.

In fact, in alpha4 line 133 in vaadin-month-calendar is empty.

**Comment by Bodhiz** [comment]
Yep you're right I was still in alpha2. My mistake, I was pretty sure to bump to alpha 4 😓
Thank you.
