### ISSUE TITLE
Add ability to customize text output

### ISSUE THREAD

**Issue by weslowsk** [vaadin/vaadin-date-picker#695]
The text output of date picker is limited to Locales and a particular date format within that Locale. For example: "1/28/2020"
I would like the ability to display "January 28, 2020" as the text output instead.

**Comment by tomivirkki** [comment]
Hi @weslowsk, you can use `parseDate` and `formatDate` functions on the `<vaadin-date-picker>` web component to produce an output in any format. See https://vaadin.com/components/vaadin-date-picker/html-examples/date-picker-localization-demos

If you need this functionality for the Flow DatePicker (Java API), there's an issue about it at https://github.com/vaadin/vaadin-date-picker-flow/issues/156
