### ISSUE TITLE
Dropdown overflows browser window on elements demo page

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-date-picker#73]
For some reason the top date picker overflows, but the latter one doesn't. https://vaadin.com/elements/-/element/vaadin-date-picker

<img width="482" alt="screen shot 2016-02-25 at 10 21 03 am" src="https://cloud.githubusercontent.com/assets/883698/13330984/2ddabd4e-dbb0-11e5-9516-17f0a80aac97.png">

**Comment by tomivirkki** [comment]
There was a regression with the alignment/sizing in alhpa 2. Fixed in https://github.com/vaadin/vaadin-date-picker/commit/c266907fe21237bb3250c1f816333d76b83952b1
