### ISSUE TITLE
V14 RC3 - unexpected behavior  - Notification is hiding DatePicker

### ISSUE THREAD

**Issue by svenruppert** [vaadin/vaadin-date-picker#755]
The example is here: https://github.com/bug-reports/vaadin-v14-001-overlay
Description: see here : https://github.com/bug-reports/vaadin-v14-001-overlay/blob/master/_data/vaadin-v14-001-overlay.gif

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-notification/issues/122
