### ISSUE TITLE
DatePicker Locale is not active all time

### ISSUE THREAD

**Issue by ugurdoksan** [vaadin/vaadin-date-picker#768]
I set a locale parameter to a datepicker.
There is nothing than a blank datepicker with locale parameter in my code.
I am using Chrome (web) as browser.

Generally I see the locale I set. But sometimes I see the default locale in the datepicker.

Here is the simple code.

`dpStartDate = new DatePicker( "" );
dpStartDate.setLocale( new Locale( "tr", "TR" ) );`

Here are the wrong and true UI s:

![mylocale](https://user-images.githubusercontent.com/24225109/45677054-f0aaf380-bb3b-11e8-9ffc-874bf5e11fb9.PNG)

Wrong locale:
![wronglocale](https://user-images.githubusercontent.com/24225109/45677059-f6083e00-bb3b-11e8-8106-3ee4bcc98c98.PNG)

**Comment by web-padawan** [comment]
Closing in favor of #768 and #761
