### ISSUE TITLE
Datepicker always invalid (Firefox)

### ISSUE THREAD

**Issue by damrath** [vaadin/vaadin-date-picker#770]
#### Description/Situation

I create date-pickers in Java, set the locale to Germany and addValueChangeListeners to them.

#### Expected Behavior:

When a value is selected an RPC is made to the java back-end and the handler is called. This works in Chrome/Chromium.

#### Actual Behavior:

In Firefox the RPC is not made and the date-picker is set to invalid.

#### Found errors:

I think this might be due to the polyfill and using the wrong `target` in datepickerConnector.js:

```Javascript
datepicker.addEventListener('blur', e => {
    if (!e.target.value && e.target.invalid) {
        console.warn("Invalid value in the DatePicker.");
    }
});
```

In chrome `e.target.value` evaluates to: `"2018-07-03"` when i select that date.
In Firefox it is empty. I assume this invalidity stops an RPC from being made.

#### Possible solution

`value` is actually stored inside the private `__target` property.
You could wrap the event using `Polyer.dom()` and using the `rootTarget` as you can see here.
![image](https://user-images.githubusercontent.com/27375330/42445155-832b6b92-8372-11e8-9fbd-abc170bee84c.png)

#### Software versions:

Vaadin: 10.0.1

Works:
- Chromium: Version 67.0.3396.87 (Official Build) Arch Linux (64-bit)
- Chrome: Version 67.0.3396.87 (Official Build) (64-bit)

Doesn't work:
- Firefox Quantum 61.0-1
- Firefox Quantum Developers Edition 62.0b4-1

OS/Kernel:
Manjaro Linux x86_64 (4.14.52-1-MANJARO)

**Comment by web-padawan** [comment]
Closing as inactive and most likely caused by web components polyfill. Please submit a new issue if the problem is still valid.
