### ISSUE TITLE
Test the performance and rendering on older devices

### ISSUE THREAD

**Issue by tehapo** [vaadin/vaadin-date-picker#89]
UX tests revealed some serious performance and rendering issues at least with Sony Xperia Z5 and iPad 2.

Needs more investigation.

**Comment by jounik** [comment]
First thing, verify with Pekka what browser he was using on his Sony phone.

**Comment by jounik** [comment]
0,5d investigation about the scope, how many users this affects.

**Comment by tehapo** [comment]
Extremely quick testing with two devices:

Samsung Galaxy Nexus (2011)
- Chrome
- Performance ok, definitely acceptable.
- No rendering issues found.

iPad Air (2013)
- Safari
- Performance really good.
- No rendering issues found.

**Comment by jounik** [comment]
iPad mini retina (2013)
- Safari
- Performance really good
- No rendering issues found

**Comment by tehapo** [comment]
Verified from Pekka that the Sony Xperia Z5 of his is actually running the Chrome browser and is upgraded to Android 6.0. And did another test to verify that the performance is still unacceptable.

The phone model was released in September 2015. Full specs of the phone here:
http://www.gsmarena.com/sony_xperia_z5-7534.php

**Comment by tehapo** [comment]
Hmm.. interesting quote from a review of that phone:

"In terms of browsing, the Xperia Z5 offers a splendid online experience. BrowserMark definitely backs up our statement, but the all JavaScript Kraken benchmark isn't quite so favorable. Naturally, we would be quick to point a finger at the built-in browser, but in the case of Sony, that is Chrome, so other forces must be at play here."

http://www.gsmarena.com/sony_xperia_z5-review-1326p5.php

**Comment by Saulis** [comment]
Tested on Simo-Pekka's brand new, pristine, out-of-the-box (even had the plastic screen shield still on) Sony Xperia Z5 and it worked perfectly.

**Comment by tehapo** [comment]
Great news! As a conclusion of this research, I would state that we only found some rendering bugs affecting iPad 2, which is too old device for us to officially support.

Closing this ticket for now. Reopen if further investigation is required.

**Comment by jounik** [comment]
Checked the Android version from Simo-Pekka, and his phone came stock with 5.1.1. So this issue might be related to Android 6.

**Comment by jounik** [comment]
We’ll update Simo-Pekka’s phone to Android 6 also, and redo the testing.

**Comment by jounik** [comment]
Finally upgraded to Android 6. No problems with Simo-Pekka’s Xperia. Tested also with the "Battery saver" setting on, didn’t affect the performance.

We still might want to come back to investigating Pekka’s Xperia more closely what’s causing the performance problem on that one individual phone, but this issue is not blocking 1.0, as all other Android 6 devices we’ve tested work great.
