### ISSUE TITLE
Make sure page-up/down doesn't skip a month

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-picker#94]
If January 31th has the keyboard focus and you hit page-down to hop to february, it should focus 28th (or whatever happens to be the last date). Currently it hops over to march so it's a bug.

According to WAI-ARIA spec:
Page Up - Moves to the same date in the previous month.
Page Down - Moves to the same date in the next month.

**Comment by jounik** [comment]
The implementation should remember the day number between navigating the moths, and select the last day of the month if it has less days (e.g. Jan 31st -> Feb 28th -> March 31st -> April 30th).
