### ISSUE TITLE
Remove the year toolbar

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-date-picker#97]
Remove the year toolbar and revise the whole date grid design accordingly.

[Date picker initial mockup](https://drive.google.com/open?id=0BzkWbWvgmkIxNGpMVlkxNUg0TlU) of the stretched layout with year toolbar removed.

**Comment by jounik** [comment]
We can start by having the blue line as the input field focus, and if the popup is wider than the input, the blue line will not span the whole popup width.

**Comment by tuomasnironen** [comment]
[Mockups for removing the toolbar](https://drive.google.com/drive/u/0/folders/0BzkWbWvgmkIxankzUnh4elJwT1E)

- Don't show the toolbar when the year scroller fits permanently visible on the screen
- On desktop the date picker popup must be aligned to touch the bottom blue line of the input when opened below. When the date picker is opened above, the alignment should be similar to e.g. combo box popup when opening above the input.
- Notice the light gray background (#eeeeee) in the toolbar

**Comment by jounik** [comment]
Is the drop shadow on the top of the scrollers intentionally missing from the mockups without the year toolbar?

Otherwise LGTM.

**Comment by tuomasnironen** [comment]
Good catch. The drop shadow should be of course included. I updated the designs accordingly.
