### ISSUE TITLE
Improve the clear X placement in the UI

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-date-picker#98]
Many test users confused the clearing functionality to closing the popup.

**Comment by tuomasnironen** [comment]
[Mockups for the clear X (iPhone 5 (narrow mobile), iPhone 6 (wide mobile), tablet)](https://drive.google.com/drive/u/0/folders/0BzkWbWvgmkIxankzUnh4elJwT1E)

- Add 2px white line to mimic the "input area" on fullscreen/mobile and attach clear X to this field
- Add calendar icon to the right top for toggling the date picker hidden (remove calendar icon from "Today")
- VISUAL NOTES
  - The calendar icon in the current implementation is a bit blurry and sized 24x22 px. It should be 24x24 px to keep the icon sharp.
  - The clear X icon is vertically 1px too low compared with e.g. the combo box clear X. The icons should stay on the same level throughout different components (as well as regarding the spacing between horizontally stacked icons)

If this revised UI design doesn't seem viable, another solution could be [placing the clear X icon inside tokens like so](https://drive.google.com/open?id=0BzkWbWvgmkIxNktkejZvLTRDWmc).

**Comment by jounik** [comment]
LGTM, seems like a great improvement. Ready for implementation in my opinion.
